// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { EditServerV01Data, EditServerV01Errors, EditServerV01Responses, EditServerV0Data, EditServerV0Errors, EditServerV0Responses, ExchangeDnsTokenV01Data, ExchangeDnsTokenV01Errors, ExchangeDnsTokenV01Responses, ExchangeDnsTokenV0Data, ExchangeDnsTokenV0Errors, ExchangeDnsTokenV0Responses, ExchangeGithubOidcTokenV01Data, ExchangeGithubOidcTokenV01Errors, ExchangeGithubOidcTokenV01Responses, ExchangeGithubOidcTokenV0Data, ExchangeGithubOidcTokenV0Errors, ExchangeGithubOidcTokenV0Responses, ExchangeGithubTokenV01Data, ExchangeGithubTokenV01Errors, ExchangeGithubTokenV01Responses, ExchangeGithubTokenV0Data, ExchangeGithubTokenV0Errors, ExchangeGithubTokenV0Responses, ExchangeHttpTokenV01Data, ExchangeHttpTokenV01Errors, ExchangeHttpTokenV01Responses, ExchangeHttpTokenV0Data, ExchangeHttpTokenV0Errors, ExchangeHttpTokenV0Responses, ExchangeOidcTokenV01Data, ExchangeOidcTokenV01Errors, ExchangeOidcTokenV01Responses, ExchangeOidcTokenV0Data, ExchangeOidcTokenV0Errors, ExchangeOidcTokenV0Responses, GetHealthV01Data, GetHealthV01Errors, GetHealthV01Responses, GetHealthV0Data, GetHealthV0Errors, GetHealthV0Responses, GetServerVersionsV01Data, GetServerVersionsV01Errors, GetServerVersionsV01Responses, GetServerVersionsV0Data, GetServerVersionsV0Errors, GetServerVersionsV0Responses, GetServerVersionV01Data, GetServerVersionV01Errors, GetServerVersionV01Responses, GetServerVersionV0Data, GetServerVersionV0Errors, GetServerVersionV0Responses, GetVersionV01Data, GetVersionV01Errors, GetVersionV01Responses, GetVersionV0Data, GetVersionV0Errors, GetVersionV0Responses, ListServersV01Data, ListServersV01Errors, ListServersV01Responses, ListServersV0Data, ListServersV0Errors, ListServersV0Responses, PingV01Data, PingV01Errors, PingV01Responses, PingV0Data, PingV0Errors, PingV0Responses, PublishServerV01Data, PublishServerV01Errors, PublishServerV01Responses, PublishServerV0Data, PublishServerV0Errors, PublishServerV0Responses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Exchange DNS signature for Registry JWT
 * Authenticate using DNS TXT record public key and signed timestamp
 */
export const exchangeDnsTokenV01 = <ThrowOnError extends boolean = false>(options: Options<ExchangeDnsTokenV01Data, ThrowOnError>) => {
    return (options.client ?? client).post<ExchangeDnsTokenV01Responses, ExchangeDnsTokenV01Errors, ThrowOnError>({
        url: '/v0.1/auth/dns',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Exchange GitHub OAuth access token for Registry JWT
 * Exchange a GitHub OAuth access token for a short-lived Registry JWT token
 */
export const exchangeGithubTokenV01 = <ThrowOnError extends boolean = false>(options: Options<ExchangeGithubTokenV01Data, ThrowOnError>) => {
    return (options.client ?? client).post<ExchangeGithubTokenV01Responses, ExchangeGithubTokenV01Errors, ThrowOnError>({
        url: '/v0.1/auth/github-at',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Exchange GitHub OIDC token for Registry JWT
 * Exchange a GitHub Actions OIDC token for a short-lived Registry JWT token
 */
export const exchangeGithubOidcTokenV01 = <ThrowOnError extends boolean = false>(options: Options<ExchangeGithubOidcTokenV01Data, ThrowOnError>) => {
    return (options.client ?? client).post<ExchangeGithubOidcTokenV01Responses, ExchangeGithubOidcTokenV01Errors, ThrowOnError>({
        url: '/v0.1/auth/github-oidc',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Exchange HTTP signature for Registry JWT
 * Authenticate using HTTP-hosted public key and signed timestamp
 */
export const exchangeHttpTokenV01 = <ThrowOnError extends boolean = false>(options: Options<ExchangeHttpTokenV01Data, ThrowOnError>) => {
    return (options.client ?? client).post<ExchangeHttpTokenV01Responses, ExchangeHttpTokenV01Errors, ThrowOnError>({
        url: '/v0.1/auth/http',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Exchange OIDC ID token for Registry JWT
 * Exchange an OIDC ID token from any configured provider for a short-lived Registry JWT token
 */
export const exchangeOidcTokenV01 = <ThrowOnError extends boolean = false>(options: Options<ExchangeOidcTokenV01Data, ThrowOnError>) => {
    return (options.client ?? client).post<ExchangeOidcTokenV01Responses, ExchangeOidcTokenV01Errors, ThrowOnError>({
        url: '/v0.1/auth/oidc',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Health check
 * Check the health status of the API
 */
export const getHealthV01 = <ThrowOnError extends boolean = false>(options?: Options<GetHealthV01Data, ThrowOnError>) => {
    return (options?.client ?? client).get<GetHealthV01Responses, GetHealthV01Errors, ThrowOnError>({
        url: '/v0.1/health',
        ...options
    });
};

/**
 * Ping
 * Simple ping endpoint
 */
export const pingV01 = <ThrowOnError extends boolean = false>(options?: Options<PingV01Data, ThrowOnError>) => {
    return (options?.client ?? client).get<PingV01Responses, PingV01Errors, ThrowOnError>({
        url: '/v0.1/ping',
        ...options
    });
};

/**
 * Publish MCP server
 * Publish a new MCP server to the registry or update an existing one
 */
export const publishServerV01 = <ThrowOnError extends boolean = false>(options: Options<PublishServerV01Data, ThrowOnError>) => {
    return (options.client ?? client).post<PublishServerV01Responses, PublishServerV01Errors, ThrowOnError>({
        url: '/v0.1/publish',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * List MCP servers
 * Get a paginated list of MCP servers from the registry
 */
export const listServersV01 = <ThrowOnError extends boolean = false>(options?: Options<ListServersV01Data, ThrowOnError>) => {
    return (options?.client ?? client).get<ListServersV01Responses, ListServersV01Errors, ThrowOnError>({
        url: '/v0.1/servers',
        ...options
    });
};

/**
 * Get all versions of an MCP server
 * Get all available versions for a specific MCP server
 */
export const getServerVersionsV01 = <ThrowOnError extends boolean = false>(options: Options<GetServerVersionsV01Data, ThrowOnError>) => {
    return (options.client ?? client).get<GetServerVersionsV01Responses, GetServerVersionsV01Errors, ThrowOnError>({
        url: '/v0.1/servers/{serverName}/versions',
        ...options
    });
};

/**
 * Get specific MCP server version
 * Get detailed information about a specific version of an MCP server. Use the special version 'latest' to get the latest version.
 */
export const getServerVersionV01 = <ThrowOnError extends boolean = false>(options: Options<GetServerVersionV01Data, ThrowOnError>) => {
    return (options.client ?? client).get<GetServerVersionV01Responses, GetServerVersionV01Errors, ThrowOnError>({
        url: '/v0.1/servers/{serverName}/versions/{version}',
        ...options
    });
};

/**
 * Edit MCP server
 * Update a specific version of an existing MCP server (admin only).
 */
export const editServerV01 = <ThrowOnError extends boolean = false>(options: Options<EditServerV01Data, ThrowOnError>) => {
    return (options.client ?? client).put<EditServerV01Responses, EditServerV01Errors, ThrowOnError>({
        url: '/v0.1/servers/{serverName}/versions/{version}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get version information
 * Returns the version, git commit, and build time of the registry application
 */
export const getVersionV01 = <ThrowOnError extends boolean = false>(options?: Options<GetVersionV01Data, ThrowOnError>) => {
    return (options?.client ?? client).get<GetVersionV01Responses, GetVersionV01Errors, ThrowOnError>({
        url: '/v0.1/version',
        ...options
    });
};

/**
 * Exchange DNS signature for Registry JWT
 * Authenticate using DNS TXT record public key and signed timestamp
 */
export const exchangeDnsTokenV0 = <ThrowOnError extends boolean = false>(options: Options<ExchangeDnsTokenV0Data, ThrowOnError>) => {
    return (options.client ?? client).post<ExchangeDnsTokenV0Responses, ExchangeDnsTokenV0Errors, ThrowOnError>({
        url: '/v0/auth/dns',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Exchange GitHub OAuth access token for Registry JWT
 * Exchange a GitHub OAuth access token for a short-lived Registry JWT token
 */
export const exchangeGithubTokenV0 = <ThrowOnError extends boolean = false>(options: Options<ExchangeGithubTokenV0Data, ThrowOnError>) => {
    return (options.client ?? client).post<ExchangeGithubTokenV0Responses, ExchangeGithubTokenV0Errors, ThrowOnError>({
        url: '/v0/auth/github-at',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Exchange GitHub OIDC token for Registry JWT
 * Exchange a GitHub Actions OIDC token for a short-lived Registry JWT token
 */
export const exchangeGithubOidcTokenV0 = <ThrowOnError extends boolean = false>(options: Options<ExchangeGithubOidcTokenV0Data, ThrowOnError>) => {
    return (options.client ?? client).post<ExchangeGithubOidcTokenV0Responses, ExchangeGithubOidcTokenV0Errors, ThrowOnError>({
        url: '/v0/auth/github-oidc',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Exchange HTTP signature for Registry JWT
 * Authenticate using HTTP-hosted public key and signed timestamp
 */
export const exchangeHttpTokenV0 = <ThrowOnError extends boolean = false>(options: Options<ExchangeHttpTokenV0Data, ThrowOnError>) => {
    return (options.client ?? client).post<ExchangeHttpTokenV0Responses, ExchangeHttpTokenV0Errors, ThrowOnError>({
        url: '/v0/auth/http',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Exchange OIDC ID token for Registry JWT
 * Exchange an OIDC ID token from any configured provider for a short-lived Registry JWT token
 */
export const exchangeOidcTokenV0 = <ThrowOnError extends boolean = false>(options: Options<ExchangeOidcTokenV0Data, ThrowOnError>) => {
    return (options.client ?? client).post<ExchangeOidcTokenV0Responses, ExchangeOidcTokenV0Errors, ThrowOnError>({
        url: '/v0/auth/oidc',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Health check
 * Check the health status of the API
 */
export const getHealthV0 = <ThrowOnError extends boolean = false>(options?: Options<GetHealthV0Data, ThrowOnError>) => {
    return (options?.client ?? client).get<GetHealthV0Responses, GetHealthV0Errors, ThrowOnError>({
        url: '/v0/health',
        ...options
    });
};

/**
 * Ping
 * Simple ping endpoint
 */
export const pingV0 = <ThrowOnError extends boolean = false>(options?: Options<PingV0Data, ThrowOnError>) => {
    return (options?.client ?? client).get<PingV0Responses, PingV0Errors, ThrowOnError>({
        url: '/v0/ping',
        ...options
    });
};

/**
 * Publish MCP server
 * Publish a new MCP server to the registry or update an existing one
 */
export const publishServerV0 = <ThrowOnError extends boolean = false>(options: Options<PublishServerV0Data, ThrowOnError>) => {
    return (options.client ?? client).post<PublishServerV0Responses, PublishServerV0Errors, ThrowOnError>({
        url: '/v0/publish',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * List MCP servers
 * Get a paginated list of MCP servers from the registry
 */
export const listServersV0 = <ThrowOnError extends boolean = false>(options?: Options<ListServersV0Data, ThrowOnError>) => {
    return (options?.client ?? client).get<ListServersV0Responses, ListServersV0Errors, ThrowOnError>({
        url: '/v0/servers',
        ...options
    });
};

/**
 * Get all versions of an MCP server
 * Get all available versions for a specific MCP server
 */
export const getServerVersionsV0 = <ThrowOnError extends boolean = false>(options: Options<GetServerVersionsV0Data, ThrowOnError>) => {
    return (options.client ?? client).get<GetServerVersionsV0Responses, GetServerVersionsV0Errors, ThrowOnError>({
        url: '/v0/servers/{serverName}/versions',
        ...options
    });
};

/**
 * Get specific MCP server version
 * Get detailed information about a specific version of an MCP server. Use the special version 'latest' to get the latest version.
 */
export const getServerVersionV0 = <ThrowOnError extends boolean = false>(options: Options<GetServerVersionV0Data, ThrowOnError>) => {
    return (options.client ?? client).get<GetServerVersionV0Responses, GetServerVersionV0Errors, ThrowOnError>({
        url: '/v0/servers/{serverName}/versions/{version}',
        ...options
    });
};

/**
 * Edit MCP server
 * Update a specific version of an existing MCP server (admin only).
 */
export const editServerV0 = <ThrowOnError extends boolean = false>(options: Options<EditServerV0Data, ThrowOnError>) => {
    return (options.client ?? client).put<EditServerV0Responses, EditServerV0Errors, ThrowOnError>({
        url: '/v0/servers/{serverName}/versions/{version}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get version information
 * Returns the version, git commit, and build time of the registry application
 */
export const getVersionV0 = <ThrowOnError extends boolean = false>(options?: Options<GetVersionV0Data, ThrowOnError>) => {
    return (options?.client ?? client).get<GetVersionV0Responses, GetVersionV0Errors, ThrowOnError>({
        url: '/v0/version',
        ...options
    });
};
