/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * One tool result to transform. `id` is the provider tool id, carried for
 * logging only — it is not unique across items (Anthropic reuses one
 * `tool_use_id` across blocks), so results are matched to inputs by position.
 */
export interface ToonEncodeItem {
  id: string
  rawContent: string
  unwrap: boolean
}

/**
 * The transformation output for one item. `normalized` is the unwrapped string
 * when unwrapping was requested and matched, else the original `raw_content`
 * (adapters tokenize it for accounting). `encoded` is the TOON encoding, or
 * `None` when the content is not parseable JSON.
 *
 * `use_nullable` makes `encoded: None` cross the boundary as an explicit JS
 * `null` (typed `string | null`) instead of an omitted key.
 */
export interface ToonEncodeResult {
  normalized: string
  encoded: string | null
}
/**
 * Transform a batch of tool results off the JS thread: optionally unwrap the
 * `[{"type":"text","text":...}]` client wrapper, parse the JSON, and encode it
 * as TOON (spec v3). Results are positional — same length and order as
 * `items`; content that is not parseable JSON yields `encoded: null` (the
 * caller keeps the original payload).
 */
export declare function toonEncodeToolResults(items: Array<ToonEncodeItem>): Promise<Array<ToonEncodeResult>>
