/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Which string an adapter tokenizes as the pre-compression baseline, selecting
 * the fused token counting (see [`toon_encode_tool_results`]). Passing `None`
 * there skips counting entirely (Anthropic and Bedrock keep their own JS
 * tokenizer); the two variants below cover the tiktoken-family adapters.
 */
export declare const enum BeforeSource {
  /**
   * Count the original `raw_content` (pre-unwrap) as the baseline — Gemini,
   * which tokenizes its serialized response, not the unwrapped inner text.
   */
  Raw = 'Raw',
  /**
   * Count the `normalized` (post-unwrap) content — every other tiktoken
   * adapter (OpenAI family, Cohere, ZhipuAI, MiniMax).
   */
  Normalized = 'Normalized'
}

/**
 * One tool result to transform. `id` is the provider tool id, carried for
 * logging only — it is not unique across items (Anthropic reuses one
 * `tool_use_id` across blocks), so results are matched to inputs by position.
 */
export interface ToonEncodeItem {
  id: string
  rawContent: string
  unwrap: boolean
}

/**
 * The transformation output for one item. `normalized` is the unwrapped string
 * when unwrapping was requested and matched, else the original `raw_content`
 * (adapters tokenize it for accounting). `encoded` is the TOON encoding, or
 * `None` when the content is not parseable JSON — or when encoding would
 * exceed the anti-amplification output budget (see `encode` module docs);
 * adapters keep the original payload either way.
 *
 * `before_tokens`/`encoded_tokens` are the cl100k counts of the baseline and
 * the compressed candidate, populated only when a [`BeforeSource`] is passed
 * AND `encoded` is `Some` (an unencodable item is never tokenized, matching
 * the adapters). Both `None` otherwise.
 *
 * `use_nullable` makes `None` fields cross the boundary as an explicit JS
 * `null` (typed `string | null` / `number | null`) instead of an omitted key.
 */
export interface ToonEncodeResult {
  normalized: string
  encoded: string | null
  beforeTokens: number | null
  encodedTokens: number | null
}
/**
 * Transform a batch of tool results off the JS thread: optionally unwrap the
 * `[{"type":"text","text":...}]` client wrapper, parse the JSON, and encode it
 * as TOON (spec v3). Results are positional — same length and order as
 * `items`; content that is not parseable JSON yields `encoded: null` (the
 * caller keeps the original payload).
 *
 * `beforeSource` selects the fused cl100k token counting: pass it to have the
 * off-thread pass populate `beforeTokens`/`encodedTokens` (`Normalized` for
 * most adapters, `Raw` for Gemini), or omit it to skip counting (Anthropic and
 * Bedrock tokenize with their own tokenizer).
 */
export declare function toonEncodeToolResults(items: Array<ToonEncodeItem>, beforeSource?: BeforeSource | undefined | null): Promise<Array<ToonEncodeResult>>
