/**
 * LLM Gateway UI Support
 * 
 * This module handles MCP UI resources in LLM Gateway responses.
 * It ensures that UIResources generated by LLMs are properly formatted
 * and compatible with the frontend MCP UI renderer.
 */

/**
 * LLM-generated UIResource structure
 */
export interface LLMUIResource {
  type: "resource";
  resource: {
    uri: string;
    mimeType: string;
    _meta?: {
      ui?: {
        resourceUri?: string;
        resourceType?: string;
      };
    };
  };
}

/**
 * Normalize UIResource from LLM response
 * Ensures consistent structure for frontend rendering
 */
export function normalizeUIResource(
  resource: any
): LLMUIResource | null {
  if (!resource) {
    return null;
  }

  // Check for resource.uri pattern
  if (resource.uri && typeof resource.uri === "string") {
    return {
      type: "resource",
      resource: {
        uri: resource.uri,
        mimeType: resource.mimeType || "text/html",
        _meta: {
          ui: {
            resourceUri: resource.uri,
            resourceType: resource.resourceType || "html",
          },
        },
      },
    };
  }

  // Check for _meta.ui.resourceUri pattern
  if (resource._meta?.ui?.resourceUri) {
    return {
      type: "resource",
      resource: {
        uri: resource._meta.ui.resourceUri,
        mimeType: resource.mimeType || "text/html",
        _meta: {
          ui: {
            resourceUri: resource._meta.ui.resourceUri,
            resourceType: resource._meta.ui.resourceType || "html",
          },
        },
      },
    };
  }

  return null;
}

/**
 * Transform LLM response to include UI resources
 * Handles both direct UIResource returns and nested structures
 */
export function transformLLMResponseForUI(
  response: any
): any {
  if (!response) {
    return response;
  }

  // Handle array of resources
  if (Array.isArray(response)) {
    return response.map((item) => transformLLMResponseForUI(item));
  }

  // Handle object response
  if (typeof response === "object") {
    // Check if this is a UIResource
    const normalized = normalizeUIResource(response);
    if (normalized) {
      return normalized;
    }

    // Recursively transform nested objects
    const transformed: any = {};
    for (const [key, value] of Object.entries(response)) {
      if (key === "content" && Array.isArray(value)) {
        transformed[key] = value.map((item) => transformLLMResponseForUI(item));
      } else if (typeof value === "object") {
        transformed[key] = transformLLMResponseForUI(value);
      } else {
        transformed[key] = value;
      }
    }
    return transformed;
  }

  return response;
}

/**
 * Check if response contains UI resources
 */
export function hasUIResources(response: any): boolean {
  if (!response) {
    return false;
  }

  if (Array.isArray(response)) {
    return response.some((item) => hasUIResources(item));
  }

  if (typeof response === "object") {
    // Check for direct UI resource
    if (normalizeUIResource(response)) {
      return true;
    }

    // Check nested properties
    for (const value of Object.values(response)) {
      if (hasUIResources(value)) {
        return true;
      }
    }
  }

  return false;
}

/**
 * Extract UI resources from response
 */
export function extractUIResources(
  response: any
): Array<{ resourceUri: string; resourceType: string }> {
  const resources: Array<{ resourceUri: string; resourceType: string }> = [];

  function traverse(obj: any) {
    if (!obj) {
      return;
    }

    if (Array.isArray(obj)) {
      obj.forEach((item) => traverse(item));
      return;
    }

    if (typeof obj === "object") {
      const normalized = normalizeUIResource(obj);
      if (normalized) {
        resources.push({
          resourceUri: normalized.resource.uri,
          resourceType: normalized.resource._meta?.ui?.resourceType || "html",
        });
      }

      for (const value of Object.values(obj)) {
        traverse(value);
      }
    }
  }

  traverse(response);
  return resources;
}

/**
 * Create UI action handler for LLM Gateway
 * Handles tool calls triggered from UI interactions
 */
export function createUIActionHandler(
  onToolCall: (toolName: string, params: Record<string, unknown>) => Promise<any>
) {
  return async (action: {
    type: string;
    toolName?: string;
    params?: Record<string, unknown>;
    prompt?: string;
    url?: string;
  }) => {
    switch (action.type) {
      case "tool":
        if (action.toolName) {
          return await onToolCall(action.toolName, action.params || {});
        }
        throw new Error("Tool name is required for tool action");

      case "prompt":
        if (action.prompt) {
          // This would be handled by the chat system
          return { type: "prompt", prompt: action.prompt };
        }
        throw new Error("Prompt is required for prompt action");

      case "link":
        if (action.url) {
          return { type: "link", url: action.url };
        }
        throw new Error("URL is required for link action");

      default:
        throw new Error(`Unknown action type: ${action.type}`);
    }
  };
}
