"use client";

import {
  ModelSelectorContent,
  type ModelSelectorContentProps,
  ModelSelectorDialog,
  type ModelSelectorDialogProps,
  ModelSelectorEmpty,
  type ModelSelectorEmptyProps,
  ModelSelectorGroup,
  type ModelSelectorGroupProps,
  ModelSelectorInput,
  type ModelSelectorInputProps,
  ModelSelectorItem,
  type ModelSelectorItemProps,
  ModelSelectorList,
  type ModelSelectorListProps,
  ModelSelectorLogo,
  type ModelSelectorLogoGroupProps,
  ModelSelectorLogoGroup,
  type ModelSelectorLogoProps,
  ModelSelectorName,
  type ModelSelectorNameProps,
  ModelSelector as RootModelSelector,
  type ModelSelectorProps,
  ModelSelectorSeparator,
  type ModelSelectorSeparatorProps,
  ModelSelectorShortcut,
  type ModelSelectorShortcutProps,
  ModelSelectorTrigger,
  type ModelSelectorTriggerProps,
} from "./model-selector";

export type {
  ModelSelectorContentProps,
  ModelSelectorDialogProps,
  ModelSelectorEmptyProps,
  ModelSelectorGroupProps,
  ModelSelectorInputProps,
  ModelSelectorItemProps,
  ModelSelectorListProps,
  ModelSelectorLogoGroupProps,
  ModelSelectorLogoProps,
  ModelSelectorNameProps,
  ModelSelectorProps,
  ModelSelectorSeparatorProps,
  ModelSelectorShortcutProps,
  ModelSelectorTriggerProps,
};

export const ModelSelector = Object.assign(RootModelSelector, {
  Content: ModelSelectorContent,
  Dialog: ModelSelectorDialog,
  Empty: ModelSelectorEmpty,
  Group: ModelSelectorGroup,
  Input: ModelSelectorInput,
  Item: ModelSelectorItem,
  List: ModelSelectorList,
  Logo: ModelSelectorLogo,
  LogoGroup: ModelSelectorLogoGroup,
  Name: ModelSelectorName,
  Separator: ModelSelectorSeparator,
  Shortcut: ModelSelectorShortcut,
  Trigger: ModelSelectorTrigger,
});
