name: Setup Rust
description: Setup Rust + install system dependencies
inputs:
  platform:
    description: ""
    required: true
  install-tauri-driver:
    description: "Whether or not to install tauri-driver"
    required: false
    default: "false"
runs:
  using: composite
  steps:
    # Cache the cargo registry to speed up the build
    # https://github.com/actions/cache/blob/main/examples.md#rust---cargo
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
        targets: ${{ inputs.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}
        components: rustfmt,clippy

    # install system dependencies that Tauri needs to compile on Linux.
    # note the extra dependencies for `tauri-driver` to run which are: `webkit2gtk-driver` and `xvfb`
    # see https://v2.tauri.app/develop/tests/webdriver/ci/
    - name: Install Tauri Ubuntu Dependencies
      if: inputs.platform == 'ubuntu-latest'
      shell: bash
      run: |
        sudo apt update && sudo apt install -y \
            libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            webkit2gtk-driver \
            xvfb

    # install the latest version of `tauri-driver`.
    # note: the tauri-driver version is independent of any other Tauri versions
    # see https://v2.tauri.app/develop/tests/webdriver/ci/
    - name: Install tauri-driver
      if: inputs.install-tauri-driver == 'true'
      shell: bash
      run: cargo install tauri-driver --locked
