/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Inject the platform baseline stylesheet, per-viewer bootstrap, and Apps SDK
 * into an owned app's HTML. `contextJson` is the caller-serialized per-viewer
 * context (identity + assigned-tool descriptors); see the core crate for the
 * trust boundary on its byte format.
 */
export declare function prepareAppEnvelope(html: string, contextJson: string): string
