archestra:
  image: archestra/platform
  imageTag: 1.0.14
  imagePullPolicy: IfNotPresent
  replicaCount: 1
  podAnnotations: {}
  nodeSelector: {}
  deploymentStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  env: {}
  envFromSecrets: []
  envFrom: []
  resources:
    requests:
      memory: 2Gi
    limits:
      memory: 3Gi
  orchestrator:
    baseImage: ''
    kubernetes:
      namespace: ''
      loadKubeconfigFromCurrentCluster: true
      kubeconfig:
        enabled: false
        secretName: ''
        mountPath: /etc/kubeconfig
      serviceAccount:
        create: true
        annotations: {}
        name: ''
        imagePullSecrets: []
      rbac:
        create: true
      mcpServerRbac:
        create: true
        additionalClusterRoleBindings: []
        additionalRoleBindings: []
  service:
    type: ClusterIP
    annotations: {}
    nodePorts:
      backend: null
      metrics: null
      frontend: null
  ingress:
    enabled: false
    annotations: {}
    spec: {}
  horizontalPodAutoscaler:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    metrics: []
    behavior: {}
  podDisruptionBudget:
    enabled: false
    minAvailable: null
    maxUnavailable: null
    unhealthyPodEvictionPolicy: null
  gkeBackendConfig:
    enabled: false
    backend:
      timeoutSec: null
      healthCheck:
        checkIntervalSec: 15
        timeoutSec: 10
        healthyThreshold: 1
        unhealthyThreshold: 10
        type: HTTP
        requestPath: /health
        port: 9000
    frontend:
      timeoutSec: null
      healthCheck:
        checkIntervalSec: 15
        timeoutSec: 10
        healthyThreshold: 1
        unhealthyThreshold: 10
        type: HTTP
        requestPath: /health
        port: 3000
postgresql:
  external_database_url: null
  enabled: true
  auth:
    database: archestra_dev
    username: archestra
  primary:
    resources:
      requests:
        cpu: 1000m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 1Gi
  image:
    repository: bitnamisecure/postgresql
    tag: latest
  global:
    security:
      allowInsecureImages: true
