import { isArchestraMcpServerTool } from "@shared";
import logger from "@/logging";
import { ToolInvocationPolicyModel } from "@/models";

/**
 * Structured result when a tool invocation is denied by policy.
 * This format matches the UI message part structure for tool errors.
 */
export interface PolicyDeniedResult {
  type: string; // "tool-<toolName>"
  state: "output-denied";
  input: Record<string, unknown>;
  errorText: string; // JSON string with method, args, reason
}

/**
 * This method will evaluate whether, based on the tool invocation policies assigned to the specified agent,
 * if the tool call is allowed or blocked.
 *
 * If this method returns non-null it is because the tool call was blocked and we are returning a structured
 * denial result that can be rendered as a tool error in the UI.
 *
 * @param toolCalls - The tool calls to evaluate
 * @param agentId - The agent ID to evaluate policies for
 * @param contextIsTrusted - Whether the context is trusted
 * @param enabledToolNames - Optional set of tool names that are enabled in the request.
 *                          If provided, tool calls not in this set will be filtered and reported as disabled.
 */
export const evaluatePolicies = async (
  toolCalls: Array<{
    toolCallName: string;
    toolCallArgs: string;
  }>,
  agentId: string,
  contextIsTrusted: boolean,
  enabledToolNames?: Set<string>,
): Promise<null | PolicyDeniedResult> => {
  logger.debug(
    { agentId, toolCallCount: toolCalls.length, contextIsTrusted },
    "[toolInvocation] evaluatePolicies: starting evaluation",
  );

  if (toolCalls.length === 0) {
    return null;
  }

  // Filter out disabled tools (not in request's tools list)
  // This is required because otherwise the tool invocation policies will be evaluated
  // for tools that are disabled during chat session.
  // Note: archestra__* tools are always enabled (built-in tools that bypass policies)
  const isToolEnabled = (toolName: string) =>
    isArchestraMcpServerTool(toolName) || enabledToolNames?.has(toolName);

  let disabledToolNames: string[] = [];
  let filteredToolCalls = toolCalls;
  if (enabledToolNames && enabledToolNames.size > 0) {
    disabledToolNames = toolCalls
      .filter((tc) => !isToolEnabled(tc.toolCallName))
      .map((tc) => tc.toolCallName);
    filteredToolCalls = toolCalls.filter((tc) =>
      isToolEnabled(tc.toolCallName),
    );
    if (disabledToolNames.length > 0) {
      logger.info(
        { disabledTools: disabledToolNames },
        "[toolInvocation] evaluatePolicies: disabled tools filtered out",
      );
    }
  }

  // If any tools were disabled, return structured denial for the first disabled tool
  if (disabledToolNames.length > 0) {
    const disabledToolCall = toolCalls.find((tc) =>
      disabledToolNames.includes(tc.toolCallName),
    );
    if (disabledToolCall) {
      let parsedInput: Record<string, unknown> = {};
      try {
        parsedInput = JSON.parse(disabledToolCall.toolCallArgs);
      } catch {
        // Keep empty object if parsing fails
      }
      return {
        type: `tool-${disabledToolCall.toolCallName}`,
        state: "output-denied",
        input: parsedInput,
        errorText: JSON.stringify({
          method: disabledToolCall.toolCallName,
          args: parsedInput,
          reason: "Tool is not enabled for this conversation",
        }),
      };
    }
  }

  // If all tools were filtered out, nothing to evaluate
  if (filteredToolCalls.length === 0) {
    return null;
  }

  // Parse all tool arguments upfront
  const parsedToolCalls = filteredToolCalls.map((toolCall) => {
    /**
     * According to the OpenAI TS SDK types.. toolCall.function.arguments mentions:
     *
     * The arguments to call the function with, as generated by the model in JSON format. Note that the model does
     * not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate
     * the arguments in your code before calling your function.
     *
     * So it is possible that the "JSON" here is malformed because the model hallucinated parameters and we
     * may need to explicitly handle this case in the future...
     */
    return {
      toolCallName: toolCall.toolCallName,
      toolInput: JSON.parse(toolCall.toolCallArgs),
    };
  });

  // Evaluate all tool calls in batch (1-2 queries total instead of N queries)
  const { isAllowed, reason, toolCallName } =
    await ToolInvocationPolicyModel.evaluateBatch(
      agentId,
      parsedToolCalls,
      contextIsTrusted,
    );

  logger.debug(
    { agentId, isAllowed, reason, toolCallName },
    "[toolInvocation] evaluatePolicies: batch evaluation result",
  );

  if (!isAllowed && toolCallName) {
    const blockedToolCall = parsedToolCalls.find(
      (tc) => tc.toolCallName === toolCallName,
    );
    const toolInput = blockedToolCall?.toolInput || {};

    logger.debug(
      { agentId, toolCallName, reason },
      "[toolInvocation] evaluatePolicies: tool invocation blocked",
    );

    return {
      type: `tool-${toolCallName}`,
      state: "output-denied",
      input: toolInput,
      errorText: JSON.stringify({
        method: toolCallName,
        args: toolInput,
        reason,
      }),
    };
  }

  logger.debug(
    { agentId, toolCallCount: toolCalls.length },
    "[toolInvocation] evaluatePolicies: all tool calls allowed",
  );
  return null;
};
