// Runs the committed TOON v3 golden corpus (generated by the Rust
// proxy-transform-core crate) through the real native addon via the
// toon-native helper, pinning exact normalized/encoded output at the JS
// boundary. Requires the built addon: mandatory in CI (the workspace builds
// native deps before vitest); locally it skips visibly when the addon is not
// built — run `pnpm test:native` from platform/backend.

import { readFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, test } from "vitest";
import { toonEncodeToolResults } from "./toon-native";

type GoldenEntry = {
  name: string;
  rawContent: string;
  unwrap: boolean;
  expected: { normalized: string; encoded: string | null };
};

const CORPUS_PATH = path.resolve(
  import.meta.dirname,
  "../../../../../archestra-rs/proxy-transform-core/tests/fixtures/golden-corpus.json",
);

const addonLoadError: unknown = await import(
  "@archestra/proxy-transform-rs"
).then(
  () => null,
  (error) => error,
);

// In CI the suite must FAIL (never skip) when the addon is missing.
const describeNative =
  addonLoadError === null || process.env.CI ? describe : describe.skip;
if (addonLoadError !== null && !process.env.CI) {
  console.warn(
    `[toon-native.golden.test] skipping: @archestra/proxy-transform-rs is not built (${String(
      addonLoadError,
    )}). Run \`pnpm test:native\` from platform/backend.`,
  );
}

describeNative("TOON v3 golden corpus through the native helper", () => {
  test("the native addon loads", () => {
    expect(addonLoadError).toBeNull();
  });

  test("every corpus entry matches its committed golden exactly", async () => {
    const corpus: GoldenEntry[] = JSON.parse(readFileSync(CORPUS_PATH, "utf8"));
    expect(corpus.length).toBeGreaterThan(0);

    const results = await toonEncodeToolResults(
      corpus.map((entry) => ({
        id: entry.name,
        rawContent: entry.rawContent,
        unwrap: entry.unwrap,
      })),
    );

    expect(results).not.toBeNull();
    // Keyed by entry name so a mismatch reports which fixture diverged.
    const actualByName = corpus.map((entry, index) => ({
      name: entry.name,
      normalized: results?.[index].normalized,
      encoded: results?.[index].encoded,
    }));
    const expectedByName = corpus.map((entry) => ({
      name: entry.name,
      normalized: entry.expected.normalized,
      encoded: entry.expected.encoded,
    }));
    expect(actualByName).toStrictEqual(expectedByName);
  });
});
