[machine]
# See the following resources for more information; basically we are disabling podman from using Rosetta
# on ARM64 (apple silicon) Macs (as this will prompt the user w/ a popup to install Rosetta). Podman falls back
# to using QEMU instead.
#
# https://podman-desktop.io/docs/podman/rosetta
# https://github.com/containers/podman/issues/22918#issuecomment-2151410875
rosetta = false
