// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ChatCompletionsData, ChatCompletionsErrors, ChatCompletionsResponses, CreateChatData, CreateChatResponses, GetChatData, GetChatErrors, GetChatResponses, GetChatsData, GetChatsResponses, GetHealthData, GetHealthResponses, GetOpenapiJsonData, GetOpenapiJsonResponses, ListProviderModelsData, ListProviderModelsErrors, ListProviderModelsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getOpenapiJson = <ThrowOnError extends boolean = false>(options?: Options<GetOpenapiJsonData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetOpenapiJsonResponses, unknown, ThrowOnError>({
        url: '/openapi.json',
        ...options
    });
};

export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({
        url: '/health',
        ...options
    });
};

/**
 * Get all chats
 */
export const getChats = <ThrowOnError extends boolean = false>(options?: Options<GetChatsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetChatsResponses, unknown, ThrowOnError>({
        url: '/api/chats',
        ...options
    });
};

/**
 * Create a new chat session
 */
export const createChat = <ThrowOnError extends boolean = false>(options?: Options<CreateChatData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateChatResponses, unknown, ThrowOnError>({
        url: '/api/chats',
        ...options
    });
};

/**
 * Get chat by ID
 */
export const getChat = <ThrowOnError extends boolean = false>(options: Options<GetChatData, ThrowOnError>) => {
    return (options.client ?? client).get<GetChatResponses, GetChatErrors, ThrowOnError>({
        url: '/api/chats/{chatId}',
        ...options
    });
};

/**
 * Create a chat completion with the specified LLM provider
 */
export const chatCompletions = <ThrowOnError extends boolean = false>(options: Options<ChatCompletionsData, ThrowOnError>) => {
    return (options.client ?? client).post<ChatCompletionsResponses, ChatCompletionsErrors, ThrowOnError>({
        url: '/v1/{provider}/chat/completions',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * List available models for the specified provider
 */
export const listProviderModels = <ThrowOnError extends boolean = false>(options: Options<ListProviderModelsData, ThrowOnError>) => {
    return (options.client ?? client).get<ListProviderModelsResponses, ListProviderModelsErrors, ThrowOnError>({
        url: '/v1/{provider}/models',
        ...options
    });
};
