// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:9000' | (string & {});
};

export type GetOpenapiJsonData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/openapi.json';
};

export type GetOpenapiJsonResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetChatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/chats';
};

export type GetChatsResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        createdAt: string;
        updatedAt: string;
        interactions: Array<{
            id: string;
            chatId: string;
            content: {
                role: 'system' | 'user' | 'assistant' | 'tool';
                content?: string | null;
                name?: string | null;
                tool_call_id?: string | null;
                tool_calls?: Array<{
                    id: string;
                    type: 'function';
                    function: {
                        name: string;
                        arguments: string;
                    };
                }> | null;
            };
            tainted: boolean;
            taintReason: string | null;
            createdAt: string;
        }>;
    }>;
};

export type GetChatsResponse = GetChatsResponses[keyof GetChatsResponses];

export type CreateChatData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/chats';
};

export type CreateChatResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type CreateChatResponse = CreateChatResponses[keyof CreateChatResponses];

export type GetChatData = {
    body?: never;
    path: {
        chatId: string;
    };
    query?: never;
    url: '/api/chats/{chatId}';
};

export type GetChatErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type GetChatError = GetChatErrors[keyof GetChatErrors];

export type GetChatResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        createdAt: string;
        updatedAt: string;
        interactions: Array<{
            id: string;
            chatId: string;
            content: {
                role: 'system' | 'user' | 'assistant' | 'tool';
                content?: string | null;
                name?: string | null;
                tool_call_id?: string | null;
                tool_calls?: Array<{
                    id: string;
                    type: 'function';
                    function: {
                        name: string;
                        arguments: string;
                    };
                }> | null;
            };
            tainted: boolean;
            taintReason: string | null;
            createdAt: string;
        }>;
    };
};

export type GetChatResponse = GetChatResponses[keyof GetChatResponses];

export type ChatCompletionsData = {
    body: {
        model: string;
        messages: Array<unknown>;
        tools?: Array<unknown>;
        tool_choice?: unknown;
        temperature?: number;
        max_tokens?: number;
        stream?: boolean;
    };
    headers: {
        'x-archestra-chat-id': string;
    };
    path: {
        provider: 'openai';
    };
    query?: never;
    url: '/v1/{provider}/chat/completions';
};

export type ChatCompletionsErrors = {
    /**
     * Default Response
     */
    400: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    403: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type ChatCompletionsError = ChatCompletionsErrors[keyof ChatCompletionsErrors];

export type ChatCompletionsResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        object: string;
        created: number;
        model: string;
        choices: Array<unknown>;
        usage?: unknown;
    };
};

export type ChatCompletionsResponse = ChatCompletionsResponses[keyof ChatCompletionsResponses];

export type ListProviderModelsData = {
    body?: never;
    path: {
        provider: 'openai';
    };
    query?: never;
    url: '/v1/{provider}/models';
};

export type ListProviderModelsErrors = {
    /**
     * Default Response
     */
    400: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type ListProviderModelsError = ListProviderModelsErrors[keyof ListProviderModelsErrors];

export type ListProviderModelsResponses = {
    /**
     * Default Response
     */
    200: {
        data: Array<unknown>;
    };
};

export type ListProviderModelsResponse = ListProviderModelsResponses[keyof ListProviderModelsResponses];
