// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:9000' | (string & {});
};

export type ChatIdResponseInput = {
    chatId: string;
};

export type ErrorResponseInput = {
    error: string | {
        message: string;
        type: string;
    };
};

export type ChatCompletionRequestInput = {
    chatId: string;
    model: string;
    messages: Array<unknown>;
    tools?: Array<unknown>;
    tool_choice?: unknown;
    temperature?: number;
    max_tokens?: number;
    stream?: boolean;
};

export type ChatCompletionResponseInput = {
    id: string;
    object: string;
    created: number;
    model: string;
    choices: Array<unknown>;
    usage?: unknown;
};

export type ModelsResponseInput = {
    data: Array<unknown>;
};

export type ChatIdResponse = {
    chatId: string;
};

export type ErrorResponse = {
    error: string | {
        message: string;
        type: string;
    };
};

export type ChatCompletionRequest = {
    chatId: string;
    model: string;
    messages: Array<unknown>;
    tools?: Array<unknown>;
    tool_choice?: unknown;
    temperature?: number;
    max_tokens?: number;
    stream?: boolean;
};

export type ChatCompletionResponse = {
    id: string;
    object: string;
    created: number;
    model: string;
    choices: Array<unknown>;
    usage?: unknown;
};

export type ModelsResponse = {
    data: Array<unknown>;
};

export type GetOpenapiJsonData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/openapi.json';
};

export type GetOpenapiJsonResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type CreateChatData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/chats';
};

export type CreateChatResponses = {
    /**
     * Default Response
     */
    200: ChatIdResponse;
};

export type CreateChatResponse = CreateChatResponses[keyof CreateChatResponses];

export type GetChatData = {
    body?: never;
    path: {
        chatId: string;
    };
    query?: never;
    url: '/api/chats/{chatId}';
};

export type GetChatErrors = {
    /**
     * Default Response
     */
    404: ErrorResponse;
};

export type GetChatError = GetChatErrors[keyof GetChatErrors];

export type GetChatResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type ChatCompletionsData = {
    body?: ChatCompletionRequestInput;
    path: {
        provider: 'openai';
    };
    query?: never;
    url: '/v1/{provider}/chat/completions';
};

export type ChatCompletionsErrors = {
    /**
     * Default Response
     */
    400: ErrorResponse;
    /**
     * Default Response
     */
    403: ErrorResponse;
    /**
     * Default Response
     */
    404: ErrorResponse;
    /**
     * Default Response
     */
    500: ErrorResponse;
};

export type ChatCompletionsError = ChatCompletionsErrors[keyof ChatCompletionsErrors];

export type ChatCompletionsResponses = {
    /**
     * Default Response
     */
    200: ChatCompletionResponse;
};

export type ChatCompletionsResponse = ChatCompletionsResponses[keyof ChatCompletionsResponses];

export type ListModelsData = {
    body?: never;
    path: {
        provider: 'openai';
    };
    query?: never;
    url: '/v1/{provider}/models';
};

export type ListModelsErrors = {
    /**
     * Default Response
     */
    400: ErrorResponse;
    /**
     * Default Response
     */
    500: ErrorResponse;
};

export type ListModelsError = ListModelsErrors[keyof ListModelsErrors];

export type ListModelsResponses = {
    /**
     * Default Response
     */
    200: ModelsResponse;
};

export type ListModelsResponse = ListModelsResponses[keyof ListModelsResponses];
