import { z } from "zod";

import { MessageParamSchema, ToolCallSchema } from "./messages";
import { ToolChoiceOptionSchema, ToolSchema } from "./tools";

/**
 * Cerebras API schemas (OpenAI-compatible)
 * https://inference-docs.cerebras.ai/api-reference/chat-completions
 */

export const ChatCompletionUsageSchema = z
  .object({
    completion_tokens: z.number(),
    prompt_tokens: z.number(),
    total_tokens: z.number(),
  })
  .describe("Token usage statistics for the completion");

export const FinishReasonSchema = z.enum([
  "stop",
  "length",
  "tool_calls",
  "content_filter",
]);

const ChoiceSchema = z
  .object({
    finish_reason: FinishReasonSchema,
    index: z.number(),
    logprobs: z.any().nullable(),
    message: z
      .object({
        content: z.string().nullable(),
        refusal: z.string().nullable().optional(),
        role: z.enum(["assistant"]),
        tool_calls: z.array(ToolCallSchema).optional(),
      })
      .describe("The assistant message generated by the model"),
  })
  .describe("A completion choice");

export const ChatCompletionRequestSchema = z
  .object({
    model: z.string(),
    messages: z.array(MessageParamSchema),
    tools: z.array(ToolSchema).optional(),
    tool_choice: ToolChoiceOptionSchema.optional(),
    temperature: z.number().nullable().optional(),
    max_tokens: z.number().nullable().optional(),
    max_completion_tokens: z.number().nullable().optional(),
    stream: z.boolean().nullable().optional(),
    top_p: z.number().nullable().optional(),
    seed: z.number().nullable().optional(),
    stop: z.union([z.string(), z.array(z.string())]).nullable().optional(),
  })
  .describe("Request body for Cerebras chat completions API");

export const ChatCompletionResponseSchema = z
  .object({
    id: z.string(),
    choices: z.array(ChoiceSchema),
    created: z.number(),
    model: z.string(),
    object: z.enum(["chat.completion"]),
    system_fingerprint: z.string().nullable().optional(),
    usage: ChatCompletionUsageSchema.optional(),
  })
  .describe("Response from Cerebras chat completions API");

export const ChatCompletionsHeadersSchema = z.object({
  "user-agent": z.string().optional().describe("The user agent of the client"),
  authorization: z
    .string()
    .describe("Bearer token for Cerebras API")
    .transform((authorization) => authorization.replace("Bearer ", "")),
});
