export const SCHEDULE_MANAGER_POLL_INTERVAL_MS = 60_000;

export const SCHEDULE_MAX_CONCURRENT_EXECUTIONS = 10;

export const SCHEDULE_DEFAULT_MISFIRE_GRACE_SECONDS = 60;

export const SCHEDULE_MIN_INTERVAL_SECONDS = 10;

export const SCHEDULE_EXECUTION_TIMEOUT_MS = 300_000;
