
[program:k3s]
command=/usr/local/bin/k3s server --disable=traefik --write-kubeconfig-mode=644 --write-kubeconfig=/root/.kube/config --data-dir=/app/data/k3s
user=root
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=0
startsecs=10
