allow_k8s_contexts(['orbstack', 'docker-desktop'])

load('ext://dotenv', 'dotenv')

# Check if .env exists, if not copy from .env.example
if not os.path.exists('.env'):
  local('cp .env.example .env')
  print("📝 Created .env from .env.example, be sure to fill in any necessary unique values (ex. API keys)")
else:
  print("📝 .env already exists, skipping copy from .env.example")

dotenv(
  './.env'
)

# pre
local_resource(
  'pnpm-install',
  cmd='pnpm install',
  deps=['./frontend/package.json', './backend/package.json'],
  labels=['pre']
)

# dev
local_resource(
  'pnpm-dev',
  serve_cmd='pnpm dev',
  labels=['dev'],
  resource_deps=['db-migrate']
)

local_resource(
  'database-gui',
  # NOTE: we need to cd into the backend directory to run the migrate command
  # because otherwise if we run the command from this directory, it is run via turbo, which does not properly
  # propogate the required environment variables (ie. DATABASE_URL)
  serve_cmd='cd backend && pnpm db:studio',
  labels=['dev'],
  resource_deps=['db-migrate']
)

local_resource(
  'lint:fix',
  cmd='pnpm type-check && pnpm lint:fix',
  labels=['dev'],
  resource_deps=['pnpm-install'],
  deps=[
    "./frontend/src",
    "./backend/src",
    "./experiments/src",
    "./biome.json"
  ]
)

local_resource(
  'lint:fix:unsafe',
  cmd='pnpm lint:fix:unsafe',
  labels=['dev'],
  resource_deps=['pnpm-install'],
  deps=["./frontend/src", "./backend/src", "./experiments/src", "./biome.json"]
)

local_resource(
  'codegen:api-client',
  cmd='pnpm codegen:api-client',
  labels=['dev'],
  resource_deps=['pnpm-install', 'pnpm-dev']
)
