apiVersion: v1
kind: Secret
metadata:
  name: archestra-pg-source-credentials
  namespace: archestra-dev
type: kubernetes.io/basic-auth
stringData:
  username: archestra
  password: archestra_dev_password
