// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:9000' | (string & {});
};

export type GeminiGenerateContentRequestSchemaInput = {
    contents: Array<{
        role: 'user' | 'model' | 'function';
        parts: Array<{
            text: string;
        } | {
            inlineData: {
                mimeType: string;
                data: string;
            };
        } | {
            fileData: {
                mimeType: string;
                fileUri: string;
            };
        } | {
            functionCall: {
                name: string;
                args: {
                    [key: string]: unknown;
                };
            };
        } | {
            functionResponse: {
                name: string;
                response: {
                    [key: string]: unknown;
                };
            };
        }>;
    }>;
    tools?: Array<{
        functionDeclarations: Array<{
            name: string;
            description?: string;
            parameters?: {
                type: 'STRING' | 'NUMBER' | 'INTEGER' | 'BOOLEAN' | 'ARRAY' | 'OBJECT' | 'NULL';
                format?: string;
                description?: string;
                nullable?: boolean;
                enum?: Array<string>;
                maxItems?: number;
                minItems?: number;
                properties?: {
                    [key: string]: unknown;
                };
                required?: Array<string>;
                items?: unknown;
            };
        }>;
    }>;
    toolConfig?: {
        functionCallingConfig: {
            mode: 'AUTO' | 'ANY' | 'NONE';
            allowedFunctionNames?: Array<string>;
        };
    };
    safetySettings?: Array<{
        category: 'HARM_CATEGORY_UNSPECIFIED' | 'HARM_CATEGORY_HATE_SPEECH' | 'HARM_CATEGORY_SEXUALLY_EXPLICIT' | 'HARM_CATEGORY_HARASSMENT' | 'HARM_CATEGORY_DANGEROUS_CONTENT';
        threshold: 'HARM_BLOCK_THRESHOLD_UNSPECIFIED' | 'BLOCK_NONE' | 'BLOCK_ONLY_HIGH' | 'BLOCK_MEDIUM_AND_ABOVE' | 'BLOCK_LOW_AND_ABOVE';
    }>;
    systemInstruction?: {
        parts: Array<{
            text: string;
        }>;
    };
    generationConfig?: {
        temperature?: number;
        topP?: number;
        topK?: number;
        candidateCount?: number;
        maxOutputTokens?: number;
        stopSequences?: Array<string>;
        responseMimeType?: string;
        responseSchema?: unknown;
    };
};

export type GeminiGenerateContentResponseSchemaInput = {
    candidates?: Array<{
        content?: {
            role: 'user' | 'model' | 'function';
            parts: Array<{
                text: string;
            } | {
                inlineData: {
                    mimeType: string;
                    data: string;
                };
            } | {
                fileData: {
                    mimeType: string;
                    fileUri: string;
                };
            } | {
                functionCall: {
                    name: string;
                    args: {
                        [key: string]: unknown;
                    };
                };
            } | {
                functionResponse: {
                    name: string;
                    response: {
                        [key: string]: unknown;
                    };
                };
            }>;
        };
        finishReason?: 'FINISH_REASON_UNSPECIFIED' | 'STOP' | 'MAX_TOKENS' | 'SAFETY' | 'RECITATION' | 'OTHER';
        index?: number;
        safetyRatings?: Array<{
            category: 'HARM_CATEGORY_UNSPECIFIED' | 'HARM_CATEGORY_HATE_SPEECH' | 'HARM_CATEGORY_SEXUALLY_EXPLICIT' | 'HARM_CATEGORY_HARASSMENT' | 'HARM_CATEGORY_DANGEROUS_CONTENT';
            probability: 'HARM_PROBABILITY_UNSPECIFIED' | 'NEGLIGIBLE' | 'LOW' | 'MEDIUM' | 'HIGH';
            blocked?: boolean;
        }>;
        citationMetadata?: {
            citations?: Array<{
                startIndex?: number;
                endIndex?: number;
                uri?: string;
                license?: string;
            }>;
        };
        tokenCount?: number;
    }>;
    promptFeedback?: {
        blockReason?: 'BLOCK_REASON_UNSPECIFIED' | 'SAFETY' | 'OTHER' | 'BLOCKLIST' | 'PROHIBITED_CONTENT';
        safetyRatings?: Array<{
            category: 'HARM_CATEGORY_UNSPECIFIED' | 'HARM_CATEGORY_HATE_SPEECH' | 'HARM_CATEGORY_SEXUALLY_EXPLICIT' | 'HARM_CATEGORY_HARASSMENT' | 'HARM_CATEGORY_DANGEROUS_CONTENT';
            probability: 'HARM_PROBABILITY_UNSPECIFIED' | 'NEGLIGIBLE' | 'LOW' | 'MEDIUM' | 'HIGH';
            blocked?: boolean;
        }>;
    };
    usageMetadata?: {
        promptTokenCount?: number;
        candidatesTokenCount?: number;
        totalTokenCount?: number;
    };
    modelVersion?: string;
};

export type OpenAiChatCompletionRequestSchemaInput = {
    model: string;
    /**
     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1186
     */
    messages: Array<{
        content: string | Array<{
            type: 'text';
            text: string;
        }>;
        role: 'developer';
        name?: string;
    } | {
        content: string | Array<{
            type: 'text';
            text: string;
        }>;
        role: 'system';
        name?: string;
    } | {
        content: string | Array<{
            type: 'text';
            text: string;
        } | {
            type: 'image_url';
            /**
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L765
             */
            image_url: {
                url: string;
                detail: 'auto' | 'low' | 'high';
            };
        } | {
            type: 'input_audio';
            /**
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L792
             */
            input_audio: {
                data: string;
                format: 'wav' | 'mp3';
            };
        } | {
            type: 'file';
            /**
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L732
             */
            file: {
                file_data?: string;
                file_id?: string;
                filename?: string;
            };
        }>;
        role: 'user';
        name?: string;
    } | {
        role: 'assistant';
        audio?: {
            id: string;
        } | unknown;
        content?: string | Array<{
            type: 'text';
            text: string;
        }> | Array<{
            type: 'refusal';
            refusal: string;
        }> | unknown;
        /**
         * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L431
         */
        function_call?: {
            arguments: string;
            name: string;
        } | unknown;
        name?: string;
        refusal?: string | unknown;
        /**
         * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1197
         */
        tool_calls?: Array<{
            id: string;
            type: 'function';
            /**
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1165
             */
            function: {
                arguments: string;
                name: string;
            };
        } | {
            id: string;
            type: 'custom';
            /**
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1128
             */
            custom: {
                input: string;
                name: string;
            };
        }>;
    } | {
        role: 'tool';
        content: string | Array<{
            type: 'text';
            text: string;
        }>;
        tool_call_id: string;
    } | {
        role: 'function';
        content: string | unknown;
        name: string;
    }>;
    /**
     *
     * A function tool that can be used to generate a response.
     *
     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1392
     *
     */
    tools?: Array<{
        type: 'function';
        /**
         * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L174
         */
        function: {
            name: string;
            description?: string;
            /**
             *
             * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L217
             *
             * The parameters the functions accepts, described as a JSON Schema object. See the
             * [guide](https://platform.openai.com/docs/guides/function-calling) for examples,
             * and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for
             * documentation about the format.
             *
             * Omitting parameters defines a function with an empty parameter list.
             *
             */
            parameters?: {
                [key: string]: unknown;
            };
            strict?: boolean | unknown;
        };
    } | {
        type: 'custom';
        custom: {
            /**
             * The name of the custom tool, used to identify it in tool calls
             */
            name: string;
            /**
             * Optional description of the custom tool, used to provide more context
             */
            description?: string;
            /**
             * The input format for the custom tool. Default is unconstrained text.
             */
            format?: {
                /**
                 * Unconstrained text format. Always `text`
                 */
                type: 'text';
            } | {
                type: 'grammar';
                /**
                 * Your chosen grammar
                 */
                grammar: {
                    /**
                     * The grammar definition
                     */
                    definition: string;
                    /**
                     * The syntax of the grammar definition
                     */
                    syntax: 'lark' | 'regex';
                };
            };
        };
    }>;
    /**
     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1405
     */
    tool_choice?: 'none' | 'auto' | 'required' | {
        type: 'allowed_tools';
        /**
         * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1455
         */
        allowed_tools: {
            /**
             *
             * Constrains the tools available to the model to a pre-defined set.
             *
             * auto allows the model to pick from among the allowed tools and generate a
             * message.
             *
             * required requires the model to call one or more of the allowed tools.
             *
             */
            mode: 'auto' | 'required';
            /**
             * A list of tool definitions that the model should be allowed to call
             */
            tools: Array<{
                [key: string]: {
                    type: 'function';
                    /**
                     * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L174
                     */
                    function: {
                        name: string;
                        description?: string;
                        /**
                         *
                         * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L217
                         *
                         * The parameters the functions accepts, described as a JSON Schema object. See the
                         * [guide](https://platform.openai.com/docs/guides/function-calling) for examples,
                         * and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for
                         * documentation about the format.
                         *
                         * Omitting parameters defines a function with an empty parameter list.
                         *
                         */
                        parameters?: {
                            [key: string]: unknown;
                        };
                        strict?: boolean | unknown;
                    };
                };
            }>;
        };
    } | {
        type: 'function';
        function: {
            name: string;
        };
    } | {
        type: 'custom';
        custom: {
            /**
             * The name of the custom tool, used to identify it in tool calls
             */
            name: string;
            /**
             * Optional description of the custom tool, used to provide more context
             */
            description?: string;
            /**
             * The input format for the custom tool. Default is unconstrained text.
             */
            format?: {
                /**
                 * Unconstrained text format. Always `text`
                 */
                type: 'text';
            } | {
                type: 'grammar';
                /**
                 * Your chosen grammar
                 */
                grammar: {
                    /**
                     * The grammar definition
                     */
                    definition: string;
                    /**
                     * The syntax of the grammar definition
                     */
                    syntax: 'lark' | 'regex';
                };
            };
        };
    };
    temperature?: number | unknown;
    max_tokens?: number | unknown;
    stream?: boolean | unknown;
};

export type OpenAiChatCompletionResponseSchemaInput = {
    id: string;
    choices: Array<{
        finish_reason: 'stop' | 'length' | 'tool_calls' | 'content_filter' | 'function_call';
        index: number;
        logprobs: unknown;
        /**
         * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1000
         */
        message: {
            content: string | unknown;
            refusal: string | unknown;
            role: 'assistant';
            annotations?: Array<unknown>;
            audio?: unknown;
            /**
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L431
             */
            function_call?: {
                arguments: string;
                name: string;
            } | unknown;
            /**
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1197
             */
            tool_calls?: Array<{
                id: string;
                type: 'function';
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1165
                 */
                function: {
                    arguments: string;
                    name: string;
                };
            } | {
                id: string;
                type: 'custom';
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1128
                 */
                custom: {
                    input: string;
                    name: string;
                };
            }>;
        };
    }>;
    created: number;
    model: string;
    object: 'chat.completion';
    server_tier?: string;
    system_fingerprint?: string | unknown;
    /**
     * https://github.com/openai/openai-node/blob/master/src/resources/completions.ts#L113
     */
    usage?: {
        completion_tokens: number;
        prompt_tokens: number;
        total_tokens: number;
        /**
         * https://github.com/openai/openai-node/blob/master/src/resources/completions.ts#L144
         */
        completion_tokens_details?: unknown;
        /**
         * https://github.com/openai/openai-node/blob/master/src/resources/completions.ts#L173
         */
        prompt_tokens_details?: unknown;
    };
};

export type GeminiGenerateContentRequestSchema = {
    contents: Array<{
        role: 'user' | 'model' | 'function';
        parts: Array<{
            text: string;
        } | {
            inlineData: {
                mimeType: string;
                data: string;
            };
        } | {
            fileData: {
                mimeType: string;
                fileUri: string;
            };
        } | {
            functionCall: {
                name: string;
                args: {
                    [key: string]: unknown;
                };
            };
        } | {
            functionResponse: {
                name: string;
                response: {
                    [key: string]: unknown;
                };
            };
        }>;
    }>;
    tools?: Array<{
        functionDeclarations: Array<{
            name: string;
            description?: string;
            parameters?: {
                type: 'STRING' | 'NUMBER' | 'INTEGER' | 'BOOLEAN' | 'ARRAY' | 'OBJECT' | 'NULL';
                format?: string;
                description?: string;
                nullable?: boolean;
                enum?: Array<string>;
                maxItems?: number;
                minItems?: number;
                properties?: {
                    [key: string]: unknown;
                };
                required?: Array<string>;
                items?: unknown;
            };
        }>;
    }>;
    toolConfig?: {
        functionCallingConfig: {
            mode: 'AUTO' | 'ANY' | 'NONE';
            allowedFunctionNames?: Array<string>;
        };
    };
    safetySettings?: Array<{
        category: 'HARM_CATEGORY_UNSPECIFIED' | 'HARM_CATEGORY_HATE_SPEECH' | 'HARM_CATEGORY_SEXUALLY_EXPLICIT' | 'HARM_CATEGORY_HARASSMENT' | 'HARM_CATEGORY_DANGEROUS_CONTENT';
        threshold: 'HARM_BLOCK_THRESHOLD_UNSPECIFIED' | 'BLOCK_NONE' | 'BLOCK_ONLY_HIGH' | 'BLOCK_MEDIUM_AND_ABOVE' | 'BLOCK_LOW_AND_ABOVE';
    }>;
    systemInstruction?: {
        parts: Array<{
            text: string;
        }>;
    };
    generationConfig?: {
        temperature?: number;
        topP?: number;
        topK?: number;
        candidateCount?: number;
        maxOutputTokens?: number;
        stopSequences?: Array<string>;
        responseMimeType?: string;
        responseSchema?: unknown;
    };
};

export type GeminiGenerateContentResponseSchema = {
    candidates?: Array<{
        content?: {
            role: 'user' | 'model' | 'function';
            parts: Array<{
                text: string;
            } | {
                inlineData: {
                    mimeType: string;
                    data: string;
                };
            } | {
                fileData: {
                    mimeType: string;
                    fileUri: string;
                };
            } | {
                functionCall: {
                    name: string;
                    args: {
                        [key: string]: unknown;
                    };
                };
            } | {
                functionResponse: {
                    name: string;
                    response: {
                        [key: string]: unknown;
                    };
                };
            }>;
        };
        finishReason?: 'FINISH_REASON_UNSPECIFIED' | 'STOP' | 'MAX_TOKENS' | 'SAFETY' | 'RECITATION' | 'OTHER';
        index?: number;
        safetyRatings?: Array<{
            category: 'HARM_CATEGORY_UNSPECIFIED' | 'HARM_CATEGORY_HATE_SPEECH' | 'HARM_CATEGORY_SEXUALLY_EXPLICIT' | 'HARM_CATEGORY_HARASSMENT' | 'HARM_CATEGORY_DANGEROUS_CONTENT';
            probability: 'HARM_PROBABILITY_UNSPECIFIED' | 'NEGLIGIBLE' | 'LOW' | 'MEDIUM' | 'HIGH';
            blocked?: boolean;
        }>;
        citationMetadata?: {
            citations?: Array<{
                startIndex?: number;
                endIndex?: number;
                uri?: string;
                license?: string;
            }>;
        };
        tokenCount?: number;
    }>;
    promptFeedback?: {
        blockReason?: 'BLOCK_REASON_UNSPECIFIED' | 'SAFETY' | 'OTHER' | 'BLOCKLIST' | 'PROHIBITED_CONTENT';
        safetyRatings?: Array<{
            category: 'HARM_CATEGORY_UNSPECIFIED' | 'HARM_CATEGORY_HATE_SPEECH' | 'HARM_CATEGORY_SEXUALLY_EXPLICIT' | 'HARM_CATEGORY_HARASSMENT' | 'HARM_CATEGORY_DANGEROUS_CONTENT';
            probability: 'HARM_PROBABILITY_UNSPECIFIED' | 'NEGLIGIBLE' | 'LOW' | 'MEDIUM' | 'HIGH';
            blocked?: boolean;
        }>;
    };
    usageMetadata?: {
        promptTokenCount?: number;
        candidatesTokenCount?: number;
        totalTokenCount?: number;
    };
    modelVersion?: string;
};

export type OpenAiChatCompletionRequestSchema = {
    model: string;
    /**
     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1186
     */
    messages: Array<{
        content: string | Array<{
            type: 'text';
            text: string;
        }>;
        role: 'developer';
        name?: string;
    } | {
        content: string | Array<{
            type: 'text';
            text: string;
        }>;
        role: 'system';
        name?: string;
    } | {
        content: string | Array<{
            type: 'text';
            text: string;
        } | {
            type: 'image_url';
            /**
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L765
             */
            image_url: {
                url: string;
                detail: 'auto' | 'low' | 'high';
            };
        } | {
            type: 'input_audio';
            /**
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L792
             */
            input_audio: {
                data: string;
                format: 'wav' | 'mp3';
            };
        } | {
            type: 'file';
            /**
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L732
             */
            file: {
                file_data?: string;
                file_id?: string;
                filename?: string;
            };
        }>;
        role: 'user';
        name?: string;
    } | {
        role: 'assistant';
        audio?: {
            id: string;
        } | unknown;
        content?: string | Array<{
            type: 'text';
            text: string;
        }> | Array<{
            type: 'refusal';
            refusal: string;
        }> | unknown;
        /**
         * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L431
         */
        function_call?: {
            arguments: string;
            name: string;
        } | unknown;
        name?: string;
        refusal?: string | unknown;
        /**
         * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1197
         */
        tool_calls?: Array<{
            id: string;
            type: 'function';
            /**
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1165
             */
            function: {
                arguments: string;
                name: string;
            };
        } | {
            id: string;
            type: 'custom';
            /**
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1128
             */
            custom: {
                input: string;
                name: string;
            };
        }>;
    } | {
        role: 'tool';
        content: string | Array<{
            type: 'text';
            text: string;
        }>;
        tool_call_id: string;
    } | {
        role: 'function';
        content: string | unknown;
        name: string;
    }>;
    /**
     *
     * A function tool that can be used to generate a response.
     *
     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1392
     *
     */
    tools?: Array<{
        type: 'function';
        /**
         * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L174
         */
        function: {
            name: string;
            description?: string;
            /**
             *
             * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L217
             *
             * The parameters the functions accepts, described as a JSON Schema object. See the
             * [guide](https://platform.openai.com/docs/guides/function-calling) for examples,
             * and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for
             * documentation about the format.
             *
             * Omitting parameters defines a function with an empty parameter list.
             *
             */
            parameters?: {
                [key: string]: unknown;
            };
            strict?: boolean | unknown;
        };
    } | {
        type: 'custom';
        custom: {
            /**
             * The name of the custom tool, used to identify it in tool calls
             */
            name: string;
            /**
             * Optional description of the custom tool, used to provide more context
             */
            description?: string;
            /**
             * The input format for the custom tool. Default is unconstrained text.
             */
            format?: {
                /**
                 * Unconstrained text format. Always `text`
                 */
                type: 'text';
            } | {
                type: 'grammar';
                /**
                 * Your chosen grammar
                 */
                grammar: {
                    /**
                     * The grammar definition
                     */
                    definition: string;
                    /**
                     * The syntax of the grammar definition
                     */
                    syntax: 'lark' | 'regex';
                };
            };
        };
    }>;
    /**
     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1405
     */
    tool_choice?: 'none' | 'auto' | 'required' | {
        type: 'allowed_tools';
        /**
         * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1455
         */
        allowed_tools: {
            /**
             *
             * Constrains the tools available to the model to a pre-defined set.
             *
             * auto allows the model to pick from among the allowed tools and generate a
             * message.
             *
             * required requires the model to call one or more of the allowed tools.
             *
             */
            mode: 'auto' | 'required';
            /**
             * A list of tool definitions that the model should be allowed to call
             */
            tools: Array<{
                [key: string]: {
                    type: 'function';
                    /**
                     * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L174
                     */
                    function: {
                        name: string;
                        description?: string;
                        /**
                         *
                         * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L217
                         *
                         * The parameters the functions accepts, described as a JSON Schema object. See the
                         * [guide](https://platform.openai.com/docs/guides/function-calling) for examples,
                         * and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for
                         * documentation about the format.
                         *
                         * Omitting parameters defines a function with an empty parameter list.
                         *
                         */
                        parameters?: {
                            [key: string]: unknown;
                        };
                        strict?: boolean | unknown;
                    };
                };
            }>;
        };
    } | {
        type: 'function';
        function: {
            name: string;
        };
    } | {
        type: 'custom';
        custom: {
            /**
             * The name of the custom tool, used to identify it in tool calls
             */
            name: string;
            /**
             * Optional description of the custom tool, used to provide more context
             */
            description?: string;
            /**
             * The input format for the custom tool. Default is unconstrained text.
             */
            format?: {
                /**
                 * Unconstrained text format. Always `text`
                 */
                type: 'text';
            } | {
                type: 'grammar';
                /**
                 * Your chosen grammar
                 */
                grammar: {
                    /**
                     * The grammar definition
                     */
                    definition: string;
                    /**
                     * The syntax of the grammar definition
                     */
                    syntax: 'lark' | 'regex';
                };
            };
        };
    };
    temperature?: number | unknown;
    max_tokens?: number | unknown;
    stream?: boolean | unknown;
};

export type OpenAiChatCompletionResponseSchema = {
    id: string;
    choices: Array<{
        finish_reason: 'stop' | 'length' | 'tool_calls' | 'content_filter' | 'function_call';
        index: number;
        logprobs: unknown;
        /**
         * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1000
         */
        message: {
            content: string | unknown;
            refusal: string | unknown;
            role: 'assistant';
            annotations?: Array<unknown>;
            audio?: unknown;
            /**
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L431
             */
            function_call?: {
                arguments: string;
                name: string;
            } | unknown;
            /**
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1197
             */
            tool_calls?: Array<{
                id: string;
                type: 'function';
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1165
                 */
                function: {
                    arguments: string;
                    name: string;
                };
            } | {
                id: string;
                type: 'custom';
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1128
                 */
                custom: {
                    input: string;
                    name: string;
                };
            }>;
        };
    }>;
    created: number;
    model: string;
    object: 'chat.completion';
    server_tier?: string;
    system_fingerprint?: string | unknown;
    /**
     * https://github.com/openai/openai-node/blob/master/src/resources/completions.ts#L113
     */
    usage?: {
        completion_tokens: number;
        prompt_tokens: number;
        total_tokens: number;
        /**
         * https://github.com/openai/openai-node/blob/master/src/resources/completions.ts#L144
         */
        completion_tokens_details?: unknown;
        /**
         * https://github.com/openai/openai-node/blob/master/src/resources/completions.ts#L173
         */
        prompt_tokens_details?: unknown;
    };
};

export type GetOpenapiJsonData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/openapi.json';
};

export type GetOpenapiJsonResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetAgentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/agents';
};

export type GetAgentsErrors = {
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type GetAgentsError = GetAgentsErrors[keyof GetAgentsErrors];

export type GetAgentsResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        name: string;
        isDemo: boolean;
        createdAt: string;
        updatedAt: string;
    }>;
};

export type GetAgentsResponse = GetAgentsResponses[keyof GetAgentsResponses];

export type CreateAgentData = {
    body: {
        name: string;
        isDemo?: boolean;
    };
    path?: never;
    query?: never;
    url: '/api/agents';
};

export type CreateAgentErrors = {
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type CreateAgentError = CreateAgentErrors[keyof CreateAgentErrors];

export type CreateAgentResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        name: string;
        isDemo: boolean;
        createdAt: string;
        updatedAt: string;
    };
};

export type CreateAgentResponse = CreateAgentResponses[keyof CreateAgentResponses];

export type DeleteAgentData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/agents/{id}';
};

export type DeleteAgentErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type DeleteAgentError = DeleteAgentErrors[keyof DeleteAgentErrors];

export type DeleteAgentResponses = {
    /**
     * Default Response
     */
    200: {
        success: boolean;
    };
};

export type DeleteAgentResponse = DeleteAgentResponses[keyof DeleteAgentResponses];

export type GetAgentData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/agents/{id}';
};

export type GetAgentErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type GetAgentError = GetAgentErrors[keyof GetAgentErrors];

export type GetAgentResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        name: string;
        isDemo: boolean;
        createdAt: string;
        updatedAt: string;
    };
};

export type GetAgentResponse = GetAgentResponses[keyof GetAgentResponses];

export type UpdateAgentData = {
    body?: {
        name?: string;
        isDemo?: boolean;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/agents/{id}';
};

export type UpdateAgentErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type UpdateAgentError = UpdateAgentErrors[keyof UpdateAgentErrors];

export type UpdateAgentResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        name: string;
        isDemo: boolean;
        createdAt: string;
        updatedAt: string;
    };
};

export type UpdateAgentResponse = UpdateAgentResponses[keyof UpdateAgentResponses];

export type GetInteractionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by agent ID
         */
        agentId?: string;
    };
    url: '/api/interactions';
};

export type GetInteractionsResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        agentId: string;
        request: OpenAiChatCompletionRequestSchema;
        response: OpenAiChatCompletionResponseSchema;
        provider: 'openai';
        createdAt: string;
    } | {
        id: string;
        agentId: string;
        request: GeminiGenerateContentRequestSchema;
        response: GeminiGenerateContentResponseSchema;
        provider: 'gemini';
        createdAt: string;
    }>;
};

export type GetInteractionsResponse = GetInteractionsResponses[keyof GetInteractionsResponses];

export type GetInteractionData = {
    body?: never;
    path: {
        interactionId: string;
    };
    query?: never;
    url: '/api/interactions/{interactionId}';
};

export type GetInteractionErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type GetInteractionError = GetInteractionErrors[keyof GetInteractionErrors];

export type GetInteractionResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        agentId: string;
        request: OpenAiChatCompletionRequestSchema;
        response: OpenAiChatCompletionResponseSchema;
        provider: 'openai';
        createdAt: string;
    } | {
        id: string;
        agentId: string;
        request: GeminiGenerateContentRequestSchema;
        response: GeminiGenerateContentResponseSchema;
        provider: 'gemini';
        createdAt: string;
    };
};

export type GetInteractionResponse = GetInteractionResponses[keyof GetInteractionResponses];

export type DeleteV1OpenaiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/openai/';
};

export type DeleteV1OpenaiResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV1OpenaiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/openai/';
};

export type GetV1OpenaiResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type HeadV1OpenaiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/openai/';
};

export type HeadV1OpenaiResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type OptionsV1OpenaiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/openai/';
};

export type OptionsV1OpenaiResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PatchV1OpenaiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/openai/';
};

export type PatchV1OpenaiResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV1OpenaiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/openai/';
};

export type PostV1OpenaiResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PutV1OpenaiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/openai/';
};

export type PutV1OpenaiResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type DeleteV1OpenaiBy__Data = {
    body?: never;
    path: {
        '*': string;
    };
    query?: never;
    url: '/v1/openai/{*}';
};

export type DeleteV1OpenaiBy__Responses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV1OpenaiBy__Data = {
    body?: never;
    path: {
        '*': string;
    };
    query?: never;
    url: '/v1/openai/{*}';
};

export type GetV1OpenaiBy__Responses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type HeadV1OpenaiBy__Data = {
    body?: never;
    path: {
        '*': string;
    };
    query?: never;
    url: '/v1/openai/{*}';
};

export type HeadV1OpenaiBy__Responses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type OptionsV1OpenaiBy__Data = {
    body?: never;
    path: {
        '*': string;
    };
    query?: never;
    url: '/v1/openai/{*}';
};

export type OptionsV1OpenaiBy__Responses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PatchV1OpenaiBy__Data = {
    body?: never;
    path: {
        '*': string;
    };
    query?: never;
    url: '/v1/openai/{*}';
};

export type PatchV1OpenaiBy__Responses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV1OpenaiBy__Data = {
    body?: never;
    path: {
        '*': string;
    };
    query?: never;
    url: '/v1/openai/{*}';
};

export type PostV1OpenaiBy__Responses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PutV1OpenaiBy__Data = {
    body?: never;
    path: {
        '*': string;
    };
    query?: never;
    url: '/v1/openai/{*}';
};

export type PutV1OpenaiBy__Responses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type OpenAiChatCompletionsWithDefaultAgentData = {
    body?: OpenAiChatCompletionRequestSchemaInput;
    headers: {
        /**
         * The user agent of the client
         */
        'user-agent'?: string;
        /**
         * Bearer token for OpenAI
         */
        authorization: string;
    };
    path?: never;
    query?: never;
    url: '/v1/openai/chat/completions';
};

export type OpenAiChatCompletionsWithDefaultAgentErrors = {
    /**
     * Default Response
     */
    400: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    403: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type OpenAiChatCompletionsWithDefaultAgentError = OpenAiChatCompletionsWithDefaultAgentErrors[keyof OpenAiChatCompletionsWithDefaultAgentErrors];

export type OpenAiChatCompletionsWithDefaultAgentResponses = {
    /**
     * Default Response
     */
    200: OpenAiChatCompletionResponseSchema;
};

export type OpenAiChatCompletionsWithDefaultAgentResponse = OpenAiChatCompletionsWithDefaultAgentResponses[keyof OpenAiChatCompletionsWithDefaultAgentResponses];

export type OpenAiChatCompletionsWithAgentData = {
    body?: OpenAiChatCompletionRequestSchemaInput;
    headers: {
        /**
         * The user agent of the client
         */
        'user-agent'?: string;
        /**
         * Bearer token for OpenAI
         */
        authorization: string;
    };
    path: {
        agentId: string;
    };
    query?: never;
    url: '/v1/openai/{agentId}/chat/completions';
};

export type OpenAiChatCompletionsWithAgentErrors = {
    /**
     * Default Response
     */
    400: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    403: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type OpenAiChatCompletionsWithAgentError = OpenAiChatCompletionsWithAgentErrors[keyof OpenAiChatCompletionsWithAgentErrors];

export type OpenAiChatCompletionsWithAgentResponses = {
    /**
     * Default Response
     */
    200: OpenAiChatCompletionResponseSchema;
};

export type OpenAiChatCompletionsWithAgentResponse = OpenAiChatCompletionsWithAgentResponses[keyof OpenAiChatCompletionsWithAgentResponses];

export type DeleteV1GeminiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/gemini/';
};

export type DeleteV1GeminiResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV1GeminiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/gemini/';
};

export type GetV1GeminiResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type HeadV1GeminiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/gemini/';
};

export type HeadV1GeminiResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type OptionsV1GeminiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/gemini/';
};

export type OptionsV1GeminiResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PatchV1GeminiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/gemini/';
};

export type PatchV1GeminiResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV1GeminiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/gemini/';
};

export type PostV1GeminiResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PutV1GeminiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/gemini/';
};

export type PutV1GeminiResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type DeleteV1GeminiBy__Data = {
    body?: never;
    path: {
        '*': string;
    };
    query?: never;
    url: '/v1/gemini/{*}';
};

export type DeleteV1GeminiBy__Responses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetV1GeminiBy__Data = {
    body?: never;
    path: {
        '*': string;
    };
    query?: never;
    url: '/v1/gemini/{*}';
};

export type GetV1GeminiBy__Responses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type HeadV1GeminiBy__Data = {
    body?: never;
    path: {
        '*': string;
    };
    query?: never;
    url: '/v1/gemini/{*}';
};

export type HeadV1GeminiBy__Responses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type OptionsV1GeminiBy__Data = {
    body?: never;
    path: {
        '*': string;
    };
    query?: never;
    url: '/v1/gemini/{*}';
};

export type OptionsV1GeminiBy__Responses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PatchV1GeminiBy__Data = {
    body?: never;
    path: {
        '*': string;
    };
    query?: never;
    url: '/v1/gemini/{*}';
};

export type PatchV1GeminiBy__Responses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV1GeminiBy__Data = {
    body?: never;
    path: {
        '*': string;
    };
    query?: never;
    url: '/v1/gemini/{*}';
};

export type PostV1GeminiBy__Responses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PutV1GeminiBy__Data = {
    body?: never;
    path: {
        '*': string;
    };
    query?: never;
    url: '/v1/gemini/{*}';
};

export type PutV1GeminiBy__Responses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostV1GeminiModelsByModelGenerateContentData = {
    body?: GeminiGenerateContentRequestSchemaInput;
    headers: {
        /**
         * The user agent of the client
         */
        'user-agent'?: string;
        /**
         * API key for Google Gemini
         */
        'x-goog-api-key': string;
    };
    path: {
        /**
         * The model to use
         */
        model: string;
    };
    query?: never;
    url: '/v1/gemini/models/{model}:generateContent';
};

export type PostV1GeminiModelsByModelGenerateContentErrors = {
    /**
     * Default Response
     */
    400: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    403: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type PostV1GeminiModelsByModelGenerateContentError = PostV1GeminiModelsByModelGenerateContentErrors[keyof PostV1GeminiModelsByModelGenerateContentErrors];

export type PostV1GeminiModelsByModelGenerateContentResponses = {
    /**
     * Default Response
     */
    200: GeminiGenerateContentResponseSchema;
};

export type PostV1GeminiModelsByModelGenerateContentResponse = PostV1GeminiModelsByModelGenerateContentResponses[keyof PostV1GeminiModelsByModelGenerateContentResponses];

export type PostV1GeminiModelsByModelStreamGenerateContentData = {
    body?: GeminiGenerateContentRequestSchemaInput;
    headers: {
        /**
         * The user agent of the client
         */
        'user-agent'?: string;
        /**
         * API key for Google Gemini
         */
        'x-goog-api-key': string;
    };
    path: {
        /**
         * The model to use
         */
        model: string;
    };
    query?: never;
    url: '/v1/gemini/models/{model}:streamGenerateContent';
};

export type PostV1GeminiModelsByModelStreamGenerateContentErrors = {
    /**
     * Default Response
     */
    400: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    403: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type PostV1GeminiModelsByModelStreamGenerateContentError = PostV1GeminiModelsByModelStreamGenerateContentErrors[keyof PostV1GeminiModelsByModelStreamGenerateContentErrors];

export type PostV1GeminiByAgentIdModelsByModelGenerateContentData = {
    body?: GeminiGenerateContentRequestSchemaInput;
    headers: {
        /**
         * The user agent of the client
         */
        'user-agent'?: string;
        /**
         * API key for Google Gemini
         */
        'x-goog-api-key': string;
    };
    path: {
        agentId: string;
        /**
         * The model to use
         */
        model: string;
    };
    query?: never;
    url: '/v1/gemini/{agentId}/models/{model}:generateContent';
};

export type PostV1GeminiByAgentIdModelsByModelGenerateContentErrors = {
    /**
     * Default Response
     */
    400: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    403: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type PostV1GeminiByAgentIdModelsByModelGenerateContentError = PostV1GeminiByAgentIdModelsByModelGenerateContentErrors[keyof PostV1GeminiByAgentIdModelsByModelGenerateContentErrors];

export type PostV1GeminiByAgentIdModelsByModelGenerateContentResponses = {
    /**
     * Default Response
     */
    200: GeminiGenerateContentResponseSchema;
};

export type PostV1GeminiByAgentIdModelsByModelGenerateContentResponse = PostV1GeminiByAgentIdModelsByModelGenerateContentResponses[keyof PostV1GeminiByAgentIdModelsByModelGenerateContentResponses];

export type PostV1GeminiByAgentIdModelsByModelStreamGenerateContentData = {
    body?: GeminiGenerateContentRequestSchemaInput;
    headers: {
        /**
         * The user agent of the client
         */
        'user-agent'?: string;
        /**
         * API key for Google Gemini
         */
        'x-goog-api-key': string;
    };
    path: {
        agentId: string;
        /**
         * The model to use
         */
        model: string;
    };
    query?: never;
    url: '/v1/gemini/{agentId}/models/{model}:streamGenerateContent';
};

export type PostV1GeminiByAgentIdModelsByModelStreamGenerateContentErrors = {
    /**
     * Default Response
     */
    400: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    403: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type PostV1GeminiByAgentIdModelsByModelStreamGenerateContentError = PostV1GeminiByAgentIdModelsByModelStreamGenerateContentErrors[keyof PostV1GeminiByAgentIdModelsByModelStreamGenerateContentErrors];

export type GetToolsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tools';
};

export type GetToolsErrors = {
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type GetToolsError = GetToolsErrors[keyof GetToolsErrors];

export type GetToolsResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        name: string;
        /**
         *
         * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L217
         *
         * The parameters the functions accepts, described as a JSON Schema object. See the
         * [guide](https://platform.openai.com/docs/guides/function-calling) for examples,
         * and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for
         * documentation about the format.
         *
         * Omitting parameters defines a function with an empty parameter list.
         *
         */
        parameters?: {
            [key: string]: unknown;
        };
        description: string | null;
        allowUsageWhenUntrustedDataIsPresent: boolean;
        dataIsTrustedByDefault: boolean;
        createdAt: string;
        updatedAt: string;
        agent: {
            id: string;
            name: string;
        };
    }>;
};

export type GetToolsResponse = GetToolsResponses[keyof GetToolsResponses];

export type UpdateToolData = {
    body?: {
        id?: string;
        agentId?: string;
        name?: string;
        /**
         *
         * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L217
         *
         * The parameters the functions accepts, described as a JSON Schema object. See the
         * [guide](https://platform.openai.com/docs/guides/function-calling) for examples,
         * and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for
         * documentation about the format.
         *
         * Omitting parameters defines a function with an empty parameter list.
         *
         */
        parameters?: {
            [key: string]: unknown;
        };
        description?: string | null;
        allowUsageWhenUntrustedDataIsPresent?: boolean;
        dataIsTrustedByDefault?: boolean;
        createdAt?: unknown;
        updatedAt?: unknown;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/tools/{id}';
};

export type UpdateToolErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type UpdateToolError = UpdateToolErrors[keyof UpdateToolErrors];

export type UpdateToolResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        agentId: string;
        name: string;
        /**
         *
         * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L217
         *
         * The parameters the functions accepts, described as a JSON Schema object. See the
         * [guide](https://platform.openai.com/docs/guides/function-calling) for examples,
         * and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for
         * documentation about the format.
         *
         * Omitting parameters defines a function with an empty parameter list.
         *
         */
        parameters?: {
            [key: string]: unknown;
        };
        description: string | null;
        allowUsageWhenUntrustedDataIsPresent: boolean;
        dataIsTrustedByDefault: boolean;
        createdAt: string;
        updatedAt: string;
    };
};

export type UpdateToolResponse = UpdateToolResponses[keyof UpdateToolResponses];

export type GetOperatorsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/autonomy-policies/operators';
};

export type GetOperatorsResponses = {
    /**
     * Default Response
     */
    200: Array<{
        value: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        label: string;
    }>;
};

export type GetOperatorsResponse = GetOperatorsResponses[keyof GetOperatorsResponses];

export type GetToolInvocationPoliciesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/autonomy-policies/tool-invocation';
};

export type GetToolInvocationPoliciesErrors = {
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type GetToolInvocationPoliciesError = GetToolInvocationPoliciesErrors[keyof GetToolInvocationPoliciesErrors];

export type GetToolInvocationPoliciesResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        toolId: string;
        argumentName: string;
        operator: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        value: string;
        action: 'allow_when_context_is_untrusted' | 'block_always';
        reason: string | null;
        createdAt: string;
        updatedAt: string;
    }>;
};

export type GetToolInvocationPoliciesResponse = GetToolInvocationPoliciesResponses[keyof GetToolInvocationPoliciesResponses];

export type CreateToolInvocationPolicyData = {
    body: {
        toolId: string;
        argumentName: string;
        operator: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        value: string;
        action: 'allow_when_context_is_untrusted' | 'block_always';
        reason?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/autonomy-policies/tool-invocation';
};

export type CreateToolInvocationPolicyErrors = {
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type CreateToolInvocationPolicyError = CreateToolInvocationPolicyErrors[keyof CreateToolInvocationPolicyErrors];

export type CreateToolInvocationPolicyResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        toolId: string;
        argumentName: string;
        operator: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        value: string;
        action: 'allow_when_context_is_untrusted' | 'block_always';
        reason: string | null;
        createdAt: string;
        updatedAt: string;
    };
};

export type CreateToolInvocationPolicyResponse = CreateToolInvocationPolicyResponses[keyof CreateToolInvocationPolicyResponses];

export type DeleteToolInvocationPolicyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/autonomy-policies/tool-invocation/{id}';
};

export type DeleteToolInvocationPolicyErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type DeleteToolInvocationPolicyError = DeleteToolInvocationPolicyErrors[keyof DeleteToolInvocationPolicyErrors];

export type DeleteToolInvocationPolicyResponses = {
    /**
     * Default Response
     */
    200: {
        success: boolean;
    };
};

export type DeleteToolInvocationPolicyResponse = DeleteToolInvocationPolicyResponses[keyof DeleteToolInvocationPolicyResponses];

export type GetToolInvocationPolicyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/autonomy-policies/tool-invocation/{id}';
};

export type GetToolInvocationPolicyErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type GetToolInvocationPolicyError = GetToolInvocationPolicyErrors[keyof GetToolInvocationPolicyErrors];

export type GetToolInvocationPolicyResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        toolId: string;
        argumentName: string;
        operator: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        value: string;
        action: 'allow_when_context_is_untrusted' | 'block_always';
        reason: string | null;
        createdAt: string;
        updatedAt: string;
    };
};

export type GetToolInvocationPolicyResponse = GetToolInvocationPolicyResponses[keyof GetToolInvocationPolicyResponses];

export type UpdateToolInvocationPolicyData = {
    body?: {
        toolId?: string;
        argumentName?: string;
        operator?: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        value?: string;
        action?: 'allow_when_context_is_untrusted' | 'block_always';
        reason?: string | null;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/autonomy-policies/tool-invocation/{id}';
};

export type UpdateToolInvocationPolicyErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type UpdateToolInvocationPolicyError = UpdateToolInvocationPolicyErrors[keyof UpdateToolInvocationPolicyErrors];

export type UpdateToolInvocationPolicyResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        toolId: string;
        argumentName: string;
        operator: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        value: string;
        action: 'allow_when_context_is_untrusted' | 'block_always';
        reason: string | null;
        createdAt: string;
        updatedAt: string;
    };
};

export type UpdateToolInvocationPolicyResponse = UpdateToolInvocationPolicyResponses[keyof UpdateToolInvocationPolicyResponses];

export type GetTrustedDataPoliciesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/trusted-data-policies';
};

export type GetTrustedDataPoliciesErrors = {
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type GetTrustedDataPoliciesError = GetTrustedDataPoliciesErrors[keyof GetTrustedDataPoliciesErrors];

export type GetTrustedDataPoliciesResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        toolId: string;
        description: string;
        attributePath: string;
        operator: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        value: string;
        action: 'block_always' | 'mark_as_trusted';
        createdAt: string;
        updatedAt: string;
    }>;
};

export type GetTrustedDataPoliciesResponse = GetTrustedDataPoliciesResponses[keyof GetTrustedDataPoliciesResponses];

export type CreateTrustedDataPolicyData = {
    body: {
        toolId: string;
        description: string;
        attributePath: string;
        operator: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        value: string;
        action: 'block_always' | 'mark_as_trusted';
    };
    path?: never;
    query?: never;
    url: '/api/trusted-data-policies';
};

export type CreateTrustedDataPolicyErrors = {
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type CreateTrustedDataPolicyError = CreateTrustedDataPolicyErrors[keyof CreateTrustedDataPolicyErrors];

export type CreateTrustedDataPolicyResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        toolId: string;
        description: string;
        attributePath: string;
        operator: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        value: string;
        action: 'block_always' | 'mark_as_trusted';
        createdAt: string;
        updatedAt: string;
    };
};

export type CreateTrustedDataPolicyResponse = CreateTrustedDataPolicyResponses[keyof CreateTrustedDataPolicyResponses];

export type DeleteTrustedDataPolicyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/trusted-data-policies/{id}';
};

export type DeleteTrustedDataPolicyErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type DeleteTrustedDataPolicyError = DeleteTrustedDataPolicyErrors[keyof DeleteTrustedDataPolicyErrors];

export type DeleteTrustedDataPolicyResponses = {
    /**
     * Default Response
     */
    200: {
        success: boolean;
    };
};

export type DeleteTrustedDataPolicyResponse = DeleteTrustedDataPolicyResponses[keyof DeleteTrustedDataPolicyResponses];

export type GetTrustedDataPolicyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/trusted-data-policies/{id}';
};

export type GetTrustedDataPolicyErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type GetTrustedDataPolicyError = GetTrustedDataPolicyErrors[keyof GetTrustedDataPolicyErrors];

export type GetTrustedDataPolicyResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        toolId: string;
        description: string;
        attributePath: string;
        operator: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        value: string;
        action: 'block_always' | 'mark_as_trusted';
        createdAt: string;
        updatedAt: string;
    };
};

export type GetTrustedDataPolicyResponse = GetTrustedDataPolicyResponses[keyof GetTrustedDataPolicyResponses];

export type UpdateTrustedDataPolicyData = {
    body?: {
        toolId?: string;
        description?: string;
        attributePath?: string;
        operator?: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        value?: string;
        action?: 'block_always' | 'mark_as_trusted';
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/trusted-data-policies/{id}';
};

export type UpdateTrustedDataPolicyErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type UpdateTrustedDataPolicyError = UpdateTrustedDataPolicyErrors[keyof UpdateTrustedDataPolicyErrors];

export type UpdateTrustedDataPolicyResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        toolId: string;
        description: string;
        attributePath: string;
        operator: 'equal' | 'notEqual' | 'contains' | 'notContains' | 'startsWith' | 'endsWith' | 'regex';
        value: string;
        action: 'block_always' | 'mark_as_trusted';
        createdAt: string;
        updatedAt: string;
    };
};

export type UpdateTrustedDataPolicyResponse = UpdateTrustedDataPolicyResponses[keyof UpdateTrustedDataPolicyResponses];

export type GetDefaultDualLlmConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/dual-llm-config/default';
};

export type GetDefaultDualLlmConfigErrors = {
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type GetDefaultDualLlmConfigError = GetDefaultDualLlmConfigErrors[keyof GetDefaultDualLlmConfigErrors];

export type GetDefaultDualLlmConfigResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        enabled: boolean;
        mainAgentPrompt: string;
        quarantinedAgentPrompt: string;
        summaryPrompt: string;
        maxRounds: number;
        createdAt: string;
        updatedAt: string;
    };
};

export type GetDefaultDualLlmConfigResponse = GetDefaultDualLlmConfigResponses[keyof GetDefaultDualLlmConfigResponses];

export type GetDualLlmConfigsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/dual-llm-config';
};

export type GetDualLlmConfigsErrors = {
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type GetDualLlmConfigsError = GetDualLlmConfigsErrors[keyof GetDualLlmConfigsErrors];

export type GetDualLlmConfigsResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        enabled: boolean;
        mainAgentPrompt: string;
        quarantinedAgentPrompt: string;
        summaryPrompt: string;
        maxRounds: number;
        createdAt: string;
        updatedAt: string;
    }>;
};

export type GetDualLlmConfigsResponse = GetDualLlmConfigsResponses[keyof GetDualLlmConfigsResponses];

export type CreateDualLlmConfigData = {
    body: {
        enabled?: boolean;
        mainAgentPrompt: string;
        quarantinedAgentPrompt: string;
        summaryPrompt: string;
        maxRounds?: number;
    };
    path?: never;
    query?: never;
    url: '/api/dual-llm-config';
};

export type CreateDualLlmConfigErrors = {
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type CreateDualLlmConfigError = CreateDualLlmConfigErrors[keyof CreateDualLlmConfigErrors];

export type CreateDualLlmConfigResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        enabled: boolean;
        mainAgentPrompt: string;
        quarantinedAgentPrompt: string;
        summaryPrompt: string;
        maxRounds: number;
        createdAt: string;
        updatedAt: string;
    };
};

export type CreateDualLlmConfigResponse = CreateDualLlmConfigResponses[keyof CreateDualLlmConfigResponses];

export type DeleteDualLlmConfigData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/dual-llm-config/{id}';
};

export type DeleteDualLlmConfigErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type DeleteDualLlmConfigError = DeleteDualLlmConfigErrors[keyof DeleteDualLlmConfigErrors];

export type DeleteDualLlmConfigResponses = {
    /**
     * Default Response
     */
    200: {
        success: boolean;
    };
};

export type DeleteDualLlmConfigResponse = DeleteDualLlmConfigResponses[keyof DeleteDualLlmConfigResponses];

export type GetDualLlmConfigData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/dual-llm-config/{id}';
};

export type GetDualLlmConfigErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type GetDualLlmConfigError = GetDualLlmConfigErrors[keyof GetDualLlmConfigErrors];

export type GetDualLlmConfigResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        enabled: boolean;
        mainAgentPrompt: string;
        quarantinedAgentPrompt: string;
        summaryPrompt: string;
        maxRounds: number;
        createdAt: string;
        updatedAt: string;
    };
};

export type GetDualLlmConfigResponse = GetDualLlmConfigResponses[keyof GetDualLlmConfigResponses];

export type UpdateDualLlmConfigData = {
    body?: {
        enabled?: boolean;
        mainAgentPrompt?: string;
        quarantinedAgentPrompt?: string;
        summaryPrompt?: string;
        maxRounds?: number;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/dual-llm-config/{id}';
};

export type UpdateDualLlmConfigErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type UpdateDualLlmConfigError = UpdateDualLlmConfigErrors[keyof UpdateDualLlmConfigErrors];

export type UpdateDualLlmConfigResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        enabled: boolean;
        mainAgentPrompt: string;
        quarantinedAgentPrompt: string;
        summaryPrompt: string;
        maxRounds: number;
        createdAt: string;
        updatedAt: string;
    };
};

export type UpdateDualLlmConfigResponse = UpdateDualLlmConfigResponses[keyof UpdateDualLlmConfigResponses];

export type GetDualLlmResultByToolCallIdData = {
    body?: never;
    path: {
        toolCallId: string;
    };
    query?: never;
    url: '/api/dual-llm-results/by-tool-call-id/{toolCallId}';
};

export type GetDualLlmResultByToolCallIdErrors = {
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type GetDualLlmResultByToolCallIdError = GetDualLlmResultByToolCallIdErrors[keyof GetDualLlmResultByToolCallIdErrors];

export type GetDualLlmResultByToolCallIdResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        agentId: string;
        toolCallId: string;
        conversations: string | number | boolean | null | {
            [key: string]: unknown;
        } | Array<unknown>;
        result: string;
        createdAt: string;
    } | null;
};

export type GetDualLlmResultByToolCallIdResponse = GetDualLlmResultByToolCallIdResponses[keyof GetDualLlmResultByToolCallIdResponses];

export type GetDualLlmResultsByInteractionData = {
    body?: never;
    path: {
        interactionId: string;
    };
    query?: never;
    url: '/api/dual-llm-results/by-interaction/{interactionId}';
};

export type GetDualLlmResultsByInteractionErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type GetDualLlmResultsByInteractionError = GetDualLlmResultsByInteractionErrors[keyof GetDualLlmResultsByInteractionErrors];

export type GetDualLlmResultsByInteractionResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        agentId: string;
        toolCallId: string;
        conversations: string | number | boolean | null | {
            [key: string]: unknown;
        } | Array<unknown>;
        result: string;
        createdAt: string;
    }>;
};

export type GetDualLlmResultsByInteractionResponse = GetDualLlmResultsByInteractionResponses[keyof GetDualLlmResultsByInteractionResponses];
