import { DEFAULT_APP_NAME, isDefaultBrandedAppName } from "@archestra/shared";
import { archestraMarkWithText } from "@/services/archestra-mark";
import type {
  SetupEnding,
  SetupScriptContext,
  ShellAgentSetup,
} from "../types";
import {
  endingMarker,
  INSTALLER_ENV,
  renderEndingNextSteps,
  renderEndingSummary,
} from "./ending";
import { describeMarketplaceContents } from "./marketplace-copy";

/** Collapse control characters so appName is safe in comments and bare echoes. */
export function sanitizeAppName(appName: string): string {
  // biome-ignore lint/suspicious/noControlCharactersInRegex: stripping them is the point
  return appName.replace(/[\x00-\x1f\x7f]+/g, " ").trim() || DEFAULT_APP_NAME;
}

/**
 * Color setup + logging helpers shared by every script. Colors are emitted
 * only when stdout is a TTY and NO_COLOR is unset, so piping the output to a
 * file or a non-interactive shell keeps it clean ANSI-free text. `say` marks
 * section headers, `ok` a success, `warn`/`err` advisory and failure lines
 * (err goes to stderr so `curl -f | bash` surfaces it).
 *
 * `cli` runs an external client CLI with its stdout/stderr detached from the
 * terminal — see the comment it carries into the script. Every
 * `claude`/`codex`/`copilot` invocation must go through it, except ones already
 * fed by a pipe (they own their stdin).
 *
 * The leading block normalizes the terminal's line discipline: a child that put
 * the terminal in raw mode on an earlier run can leave it wedged (output no
 * longer returns to column 0 and every line marches right), so we reset it up
 * front and restore it on exit — the script both survives a wedged terminal and
 * never hands one back.
 */
const BASH_SCRIPT_HELPERS = `# If stdout is a terminal, make sure its line discipline is sane: a CLI that
# grabbed it (raw mode) on a previous run can leave newline handling off, which
# staircases every following line to the right. Reset on entry so this run reads
# cleanly, and on exit so the shell gets a usable terminal back.
if [ -t 1 ] && command -v stty >/dev/null 2>&1 && { : </dev/tty; } 2>/dev/null; then
  stty sane </dev/tty 2>/dev/null || true
  trap 'stty sane </dev/tty 2>/dev/null || true' EXIT
fi
if [ -t 1 ] && [ -z "\${NO_COLOR:-}" ]; then
  ARCH_C_RESET=$'\\033[0m'; ARCH_C_HEAD=$'\\033[1;36m'; ARCH_C_OK=$'\\033[1;32m'
  ARCH_C_WARN=$'\\033[1;33m'; ARCH_C_ERR=$'\\033[1;31m'
else
  ARCH_C_RESET=''; ARCH_C_HEAD=''; ARCH_C_OK=''; ARCH_C_WARN=''; ARCH_C_ERR=''
fi
say()  { printf '\\n%s==> %s%s\\n' "$ARCH_C_HEAD" "$1" "$ARCH_C_RESET"; }
ok()   { printf '%s==>%s %s\\n' "$ARCH_C_OK" "$ARCH_C_RESET" "$1"; }
warn() { printf '%swarning:%s %s\\n' "$ARCH_C_WARN" "$ARCH_C_RESET" "$1"; }
err()  { printf '%serror:%s %s\\n' "$ARCH_C_ERR" "$ARCH_C_RESET" "$1" >&2; }

# Run a client CLI (claude/codex/copilot) so it prints plain text instead of
# driving the terminal. Those CLIs render a full-screen TUI whenever stdout is a
# tty: they probe the terminal for its theme/capabilities and position output
# with absolute cursor moves, both of which assume they own the screen. Under
# "curl | bash" they don't — this script is already writing to it — so the probe
# replies echo in as stray text ("rgb:1e1e/1e1e/1e1e", "^[[?1;2c") and the
# cursor moves land at the wrong column, cascading every following line to the
# right. Piping stdout+stderr through cat makes stdout a pipe, not a tty, so each
# CLI falls back to linear plain-text output; </dev/null keeps them off this
# script's own stdin (the download pipe). pipefail preserves their exit status.
cli() { "$@" </dev/null 2>&1 | cat; }`;

/** What the banner says the setup covers, in the ending's words. */
function setupParts(ctx: SetupScriptContext): string[] {
  const parts: string[] = [];
  if (ctx.mcp) parts.push("Tools");
  if (ctx.proxy) parts.push(`LLM proxy (${ctx.proxy.providerLabel})`);
  if (ctx.skills) {
    const { hasSkills, hasPlugins } = describeMarketplaceContents(ctx.skills);
    if (hasSkills) parts.push("Skills");
    if (hasPlugins) parts.push("Plugins");
  }
  return parts;
}

export function bashHeader(
  ctx: SetupScriptContext,
  agent: ShellAgentSetup,
): string {
  const { label, binary } = agent;
  const requireBinary = binary
    ? `
if ! command -v ${binary} >/dev/null 2>&1; then
  err "the '${binary}' CLI was not found on PATH. Install ${label} first, then re-run this command."
  exit 1
fi`
    : "";

  return `#!/usr/bin/env bash
# ${ctx.appName} setup for ${label}.
# Generated by the ${ctx.appName} /connection page. This script contains
# credentials — do not share or commit it.
set -euo pipefail

${BASH_SCRIPT_HELPERS}

${bashBanner(ctx, label)}${requireBinary}`;
}

/**
 * Splash printed at the very top of every script: the Archestra ASCII mark
 * (only when not white-labeled — printing the Archestra icon under a custom
 * brand would be wrong) plus a portable, plain-ASCII details block. Printed
 * through a quoted heredoc so nothing in it is ever expanded by bash.
 */
function bashBanner(ctx: SetupScriptContext, label: string): string {
  const configures = setupParts(ctx);

  // The one canonical Archestra mark (shared with the startup guards), block/
  // quadrant glyphs that render as solid shapes in any UTF-8 terminal.
  const logo = isDefaultBrandedAppName(ctx.appName)
    ? archestraMarkWithText({ appName: ctx.appName }).join("\n")
    : `   ${ctx.appName}
   Secure access to your AI tools`;

  const details = [
    `   Connecting: ${label}`,
    configures.length > 0 ? `   Sets up:    ${configures.join(", ")}` : null,
  ]
    .filter(Boolean)
    .join("\n");

  return `cat <<'ARCHESTRA_BANNER'

${logo}

${details}
ARCHESTRA_BANNER`;
}

/**
 * The ending, printed only when the script runs on its own: under the Node
 * installer (INSTALLER_ENV set) the installer prints it from the marker line.
 */
export function bashFooter(ending: SetupEnding): string {
  return `${endingMarker(ending)}
if [ -z "\${${INSTALLER_ENV}:-}" ]; then
  echo
  cat <<'ARCHESTRA_NEXT'
${renderEndingSummary(ending)}
ARCHESTRA_NEXT
${
  ending.optionalInstructions
    ? `node <<'ARCHESTRA_OPTIONAL'
${ending.optionalInstructions}
ARCHESTRA_OPTIONAL
`
    : ""
}cat <<'ARCHESTRA_NEXT'
${renderEndingNextSteps(ending)}
ARCHESTRA_NEXT
fi`;
}

/**
 * Color setup + logging helpers. Colors are emitted only when NO_COLOR is
 * unset. `Say` marks section headers, `Ok` a success, `Warn`/`Err` advisory
 * and failure lines. A native command's non-zero exit is demoted from a
 * terminating error ($PSNativeCommandUseErrorActionPreference = $false); its
 * stderr — which $ErrorActionPreference='Stop' still promotes to a terminating
 * error on Windows PowerShell 5.1, past 2>$null — is instead swallowed per-call
 * (try/catch around the idempotent MCP remove) so a re-run never aborts.
 */
const POWERSHELL_SCRIPT_HELPERS = `$ErrorActionPreference = 'Stop'
$PSNativeCommandUseErrorActionPreference = $false
$ArchUseColor = [string]::IsNullOrEmpty($env:NO_COLOR)
# Header-mark capability. Windows Terminal and PowerShell 7 render the Unicode
# braille mark (the exact macOS/Linux/guard logo); the legacy console (Windows
# PowerShell 5.1 in conhost) mojibakes braille glyphs on its OEM codepage, so it
# falls back to the ASCII mark. Switching this session to UTF-8 is best-effort
# and harmless if it fails — it only affects how the banner below is drawn.
$ArchUtf8 = $false
try {
  if ($env:WT_SESSION -or $PSVersionTable.PSVersion.Major -ge 6) {
    [Console]::OutputEncoding = [System.Text.UTF8Encoding]::new()
    $OutputEncoding = [System.Text.UTF8Encoding]::new()
    $ArchUtf8 = $true
  }
} catch { }
function Say($m)  { Write-Host ''; if ($ArchUseColor) { Write-Host ('==> ' + $m) -ForegroundColor Cyan } else { Write-Host ('==> ' + $m) } }
function Ok($m)   { if ($ArchUseColor) { Write-Host ('==> ' + $m) -ForegroundColor Green } else { Write-Host ('==> ' + $m) } }
function Warn($m) { if ($ArchUseColor) { Write-Host ('warning: ' + $m) -ForegroundColor Yellow } else { Write-Host ('warning: ' + $m) } }
function Err($m)  { if ($ArchUseColor) { Write-Host ('error: ' + $m) -ForegroundColor Red } else { Write-Host ('error: ' + $m) } }`;

export function powerShellHeader(
  ctx: SetupScriptContext,
  agent: ShellAgentSetup,
): string {
  const { label, binary } = agent;
  const requireBinary = binary
    ? `
if (-not (Get-Command ${binary} -ErrorAction SilentlyContinue)) {
  Err "the '${binary}' CLI was not found on PATH. Install ${label} first, then re-run this command."
  exit 1
}`
    : "";

  return `# ${ctx.appName} setup for ${label}.
# Generated by the ${ctx.appName} /connection page. This script contains
# credentials — do not share or commit it.
${POWERSHELL_SCRIPT_HELPERS}

${powerShellBanner(ctx, label)}${requireBinary}`;
}

/**
 * Splash printed at the top of every script: the Archestra mark plus a plain
 * details block, emitted through single-quoted here-strings so nothing in them
 * is ever expanded by PowerShell. The mark is the exact canonical logo (shared
 * with the macOS/Linux banner and every startup guard) when the host can render
 * UTF-8 braille glyphs, and the portable ASCII rendition of the same composition
 * otherwise — chosen at runtime by $ArchUtf8 (set in POWERSHELL_SCRIPT_HELPERS) so a legacy
 * `irm | iex` console never mojibakes.
 */
function powerShellBanner(ctx: SetupScriptContext, label: string): string {
  const configures = setupParts(ctx);

  const details = [
    `   Connecting: ${label}`,
    configures.length > 0 ? `   Sets up:    ${configures.join(", ")}` : null,
  ]
    .filter(Boolean)
    .join("\n");

  const markBlock = isDefaultBrandedAppName(ctx.appName)
    ? `if ($ArchUtf8) {
Write-Host @'

${archestraMarkWithText({ appName: ctx.appName, variant: "unicode" }).join("\n")}
'@
} else {
Write-Host @'

${archestraMarkWithText({ appName: ctx.appName, variant: "ascii" }).join("\n")}
'@
}`
    : `Write-Host @'

   ${ctx.appName}
   Secure access to your AI tools
'@`;

  return `${markBlock}
Write-Host @'

${details}
'@`;
}

/** The PowerShell twin of bashFooter. */
export function powerShellFooter(ending: SetupEnding): string {
  return `${endingMarker(ending)}
if (-not $env:${INSTALLER_ENV}) {
Write-Host @'

${renderEndingSummary(ending)}
'@
${
  ending.optionalInstructions
    ? `@'
${ending.optionalInstructions}
'@ | node
`
    : ""
}Write-Host @'
${renderEndingNextSteps(ending)}
'@
}`;
}
