"use client";

import {
  PromptInputActionAddAttachments,
  PromptInputActionMenu,
  PromptInputActionMenuContent,
  PromptInputActionMenuItem,
  PromptInputActionMenuTrigger,
  PromptInputAttachment,
  PromptInputAttachments,
  PromptInputBody,
  PromptInputButton,
  PromptInputCommand,
  PromptInputCommandEmpty,
  PromptInputCommandGroup,
  PromptInputCommandInput,
  PromptInputCommandItem,
  PromptInputCommandList,
  PromptInputCommandSeparator,
  PromptInputFooter,
  PromptInputHeader,
  PromptInputHoverCard,
  PromptInputHoverCardContent,
  PromptInputHoverCardTrigger,
  PromptInputProvider,
  PromptInput as RootPromptInput,
  PromptInputSelect,
  PromptInputSelectContent,
  PromptInputSelectItem,
  PromptInputSelectTrigger,
  PromptInputSelectValue,
  PromptInputSpeechButton,
  PromptInputSubmit,
  PromptInputTab,
  PromptInputTabBody,
  PromptInputTabItem,
  PromptInputTabLabel,
  PromptInputTabsList,
  PromptInputTextarea,
  PromptInputTools,
  usePromptInputAttachments,
  usePromptInputController,
  useProviderAttachments,
} from "./prompt-input";

export type {
  AttachmentsContext,
  PromptInputActionAddAttachmentsProps,
  PromptInputActionMenuContentProps,
  PromptInputActionMenuItemProps,
  PromptInputActionMenuProps,
  PromptInputActionMenuTriggerProps,
  PromptInputAttachmentProps,
  PromptInputAttachmentsProps,
  PromptInputBodyProps,
  PromptInputButtonProps,
  PromptInputCommandEmptyProps,
  PromptInputCommandGroupProps,
  PromptInputCommandInputProps,
  PromptInputCommandItemProps,
  PromptInputCommandListProps,
  PromptInputCommandProps,
  PromptInputCommandSeparatorProps,
  PromptInputControllerProps,
  PromptInputFooterProps,
  PromptInputHeaderProps,
  PromptInputHoverCardContentProps,
  PromptInputHoverCardProps,
  PromptInputHoverCardTriggerProps,
  PromptInputMessage,
  PromptInputProps,
  PromptInputProviderProps,
  PromptInputSelectContentProps,
  PromptInputSelectItemProps,
  PromptInputSelectProps,
  PromptInputSelectTriggerProps,
  PromptInputSelectValueProps,
  PromptInputSpeechButtonProps,
  PromptInputSubmitProps,
  PromptInputTabBodyProps,
  PromptInputTabItemProps,
  PromptInputTabLabelProps,
  PromptInputTabProps,
  PromptInputTabsListProps,
  PromptInputTextareaProps,
  PromptInputToolsProps,
  TextInputContext,
} from "./prompt-input";

export {
  usePromptInputAttachments,
  usePromptInputController,
  useProviderAttachments,
};

const PromptInputActionMenuCompound = Object.assign(PromptInputActionMenu, {
  Content: PromptInputActionMenuContent,
  Item: PromptInputActionMenuItem,
  Trigger: PromptInputActionMenuTrigger,
});

const PromptInputCommandCompound = Object.assign(PromptInputCommand, {
  Empty: PromptInputCommandEmpty,
  Group: PromptInputCommandGroup,
  Input: PromptInputCommandInput,
  Item: PromptInputCommandItem,
  List: PromptInputCommandList,
  Separator: PromptInputCommandSeparator,
});

const PromptInputHoverCardCompound = Object.assign(PromptInputHoverCard, {
  Content: PromptInputHoverCardContent,
  Trigger: PromptInputHoverCardTrigger,
});

const PromptInputSelectCompound = Object.assign(PromptInputSelect, {
  Content: PromptInputSelectContent,
  Item: PromptInputSelectItem,
  Trigger: PromptInputSelectTrigger,
  Value: PromptInputSelectValue,
});

export const PromptInput = Object.assign(RootPromptInput, {
  ActionAddAttachments: PromptInputActionAddAttachments,
  ActionMenu: PromptInputActionMenuCompound,
  Attachment: PromptInputAttachment,
  Attachments: PromptInputAttachments,
  Body: PromptInputBody,
  Button: PromptInputButton,
  Command: PromptInputCommandCompound,
  Footer: PromptInputFooter,
  Header: PromptInputHeader,
  HoverCard: PromptInputHoverCardCompound,
  Provider: PromptInputProvider,
  Select: PromptInputSelectCompound,
  SpeechButton: PromptInputSpeechButton,
  Submit: PromptInputSubmit,
  Tab: PromptInputTab,
  TabBody: PromptInputTabBody,
  TabItem: PromptInputTabItem,
  TabLabel: PromptInputTabLabel,
  TabsList: PromptInputTabsList,
  Textarea: PromptInputTextarea,
  Tools: PromptInputTools,
});
