/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface ArtifactBytes {
  dataBase64: string
  sizeBytes: number
}

export interface CheckSessionInput {
  traceparent?: string
}

export interface CommandExecution {
  stdout: string
  stderr: string
  exitCode: number
  durationMs: number
  timedOut: boolean
  truncated: boolean
}

export interface Limits {
  outputBytesLimit: number
  fileSizeLimitBytes: number
  cpuSeconds: number
  memoryBytes: number
  maxProcesses: number
}

export interface ReadArtifactInput {
  traceparent?: string
  snapshots: Array<SnapshotFile>
  replayCommands: Array<ReplayCommand>
  limits: Limits
  path: string
  extraAptPackages: Array<string>
}

export interface ReplayCommand {
  command: string
  cwd?: string
  timeoutSeconds: number
}

export interface RunSandboxInput {
  traceparent?: string
  snapshots: Array<SnapshotFile>
  replayCommands: Array<ReplayCommand>
  limits: Limits
  command: string
  cwd: string
  timeoutSeconds: number
  /** optional debian packages to install on top of the warm base before this run. */
  extraAptPackages: Array<string>
}

export interface SnapshotFile {
  skillName: string
  path: string
  encoding: string
  content: string
}
export declare function checkSession(input?: CheckSessionInput | undefined | null): Promise<void>

export declare function readArtifact(input: ReadArtifactInput): Promise<ArtifactBytes>

export declare function runSandbox(input: RunSandboxInput): Promise<CommandExecution>
