import { chromium } from "@playwright/test";
const SHOT = "/tmp/claude-1001/-home-claude-archestra-platform/32172742-efb2-455b-9cda-8da4742e1055/scratchpad";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
await p.goto("http://localhost:3000/chat", { waitUntil: "commit" });
await p.waitForTimeout(12000);
await p.screenshot({ path: `${SHOT}/dbg.png` });
console.log("url:", p.url());
console.log("textareas:", await p.locator("textarea").count());
console.log("testid:", await p.getByTestId("chat-prompt-textarea").count());
console.log("lock btns:", await p.getByRole("button", { name: /locked/i }).count());
await b.close();
