import { chromium } from "@playwright/test";
const [url, out, w, h] = process.argv.slice(2);
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: +(w||1440), height: +(h||900) } });
const errs = [];
p.on("console", m => { if (m.type()==="error") errs.push(m.text()); });
await p.goto("http://localhost:3000/", { waitUntil: "domcontentloaded", timeout: 60000 });
await p.waitForTimeout(5000);
await p.goto("http://localhost:3000"+url, { waitUntil: "domcontentloaded", timeout: 60000 });
await p.waitForTimeout(6000);
await p.screenshot({ path: out, fullPage: true });
console.log("URL:", p.url());
console.log("ERRORS:", JSON.stringify(errs.slice(0,10), null, 1));
await b.close();
