import { chromium } from "@playwright/test";
const [url, out, w, h] = process.argv.slice(2);
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: Number(w), height: Number(h) } });
const p = await ctx.newPage();
await p.goto("http://localhost:3000/", { waitUntil: "domcontentloaded" });
await p.waitForTimeout(6000);
await p.goto(url, { waitUntil: "domcontentloaded" });
await p.waitForTimeout(8000);
await p.screenshot({ path: out });
await b.close();
