"use strict";
const { loadNativeBinding, wrapAsync } = require("@archestra/napi-loader");
const binding = loadNativeBinding({ dir: __dirname, crateName: "openappa_rs", packageName: "@archestra/openappa-rs" });
module.exports.initializeOpenappa = wrapAsync(binding, "initializeOpenappa");
module.exports.dispatchHook = wrapAsync(binding, "dispatchHook");
module.exports.executeRemedyByOffer = wrapAsync(binding, "executeRemedyByOffer");
module.exports.loadOfferReview = wrapAsync(binding, "loadOfferReview");
module.exports.loadChildReturns = wrapAsync(binding, "loadChildReturns");
module.exports.validateOpenappaPolicy = wrapAsync(binding, "validateOpenappaPolicy");
module.exports.composeOpenappaPolicy = wrapAsync(binding, "composeOpenappaPolicy");
module.exports.parseOpenappaDeclarations = wrapAsync(binding, "parseOpenappaDeclarations");
module.exports.editOpenappaPolicy = wrapAsync(binding, "editOpenappaPolicy");
module.exports.listBundledOpenappaBatteries = wrapAsync(binding, "listBundledOpenappaBatteries");
module.exports.inspectOpenappaBattery = wrapAsync(binding, "inspectOpenappaBattery");
