/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function dispatchHook(input: string, policyContent?: string | undefined | null): Promise<string>

export declare function initializeOpenappa(databaseUrl: string, policyContent: string): Promise<void>

export declare function validateOpenappaPolicy(content: string): Promise<Array<string>>
