name: Build e2e test CI container image

on:
  # TODO: remove this line when done testing..
  pull_request:
  push:
    branches:
      - main
    paths:
      - .github/Dockerfile.e2e-tests

jobs:
  build-and-push:
    name: Build and push container image
    runs-on: blacksmith-16vcpu-ubuntu-2404
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Authenticate to Google Artifact Registry
        uses: ./.github/actions/auth-to-gar
        with:
          service_account: ${{ secrets.DEVELOPMENT_OAUTH_PROXY_RELEASER_GCP_SERVICE_ACCOUNT_NAME }}
          workload_identity_provider: ${{ secrets.DEVELOPMENT_OAUTH_PROXY_RELEASER_GCP_WORKLOAD_IDENTITY_PROVIDER_IDENTIFIER }}

      - name: Setup Blacksmith Builder
        uses: useblacksmith/setup-docker-builder@f9b57e1c7d5a57eed0b5609e1ffeadbf3bb0b726 # v1.1.0

      - name: Build and push Docker image
        uses: useblacksmith/build-push-action@30c71162f16ea2c27c3e21523255d209b8b538c1 # v2
        with:
          context: .
          file: .github/Dockerfile.e2e-tests
          push: true
          tags: |
            europe-west1-docker.pkg.dev/friendly-path-465518-r6/archestra-public/e2e-test-ci:latest
