name: Linting and Tests

on:
  pull_request:
    branches:
      - main

jobs:
  rust-linting-and-tests:
    name: Rust Linting and Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          platform: ${{ matrix.platform }}

      - name: Check Rust formatting
        working-directory: desktop/src-tauri
        run: cargo fmt --check

      - name: Run Clippy Linting only own code
        working-directory: desktop/src-tauri
        run: cargo clippy --workspace --all-targets --all-features --exclude tauri-mcp -- -D warnings

      - name: Run tests
        working-directory: desktop/src-tauri
        run: cargo test

  frontend-linting-and-tests:
    name: Frontend Linting and Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup frontend dependencies
        uses: ./.github/actions/setup-frontend

      - name: Check prettier formatting
        working-directory: desktop
        run: pnpm prettier --check .

      - name: Run tests
        working-directory: desktop
        run: pnpm test

      - name: Build
        working-directory: desktop
        run: pnpm build

  verify-openapi-schema-is-up-to-date:
    name: Verify Open API schema is up to date
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          platform: ubuntu-latest

      - name: Setup frontend dependencies
        uses: ./.github/actions/setup-frontend

      - name: Generate OpenAPI schema
        working-directory: desktop/src-tauri
        run: cargo run --bin dump_openapi

      - name: Generate TypeScript client
        working-directory: desktop
        run: pnpm codegen

      - name: Check for uncommitted changes
        working-directory: desktop
        run: |
          if ! git diff --exit-code; then
            echo "❌ OpenAPI schema or TypeScript client is out of date!"
            echo "Please run the following commands and commit the changes:"
            echo "  cd desktop/src-tauri && cargo run --bin dump_openapi"
            echo "  cd desktop && pnpm codegen"
            exit 1
          fi
          echo "✅ OpenAPI schema and TypeScript client are up to date"
