name: Linting and Tests

on:
  pull_request:
    branches:
      - main

jobs:
  rust-linting-and-tests:
    name: Rust Linting and Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt,clippy

      - name: Check Rust formatting
        working-directory: desktop/src-tauri
        run: cargo fmt --check

      # - name: Run Clippy Linting
      #   working-directory: desktop/src-tauri
      # run: cargo clippy --all-targets --all-features -- -D warnings
      # run: cargo clippy --all-features -- -D warnings

      - name: Run tests
        working-directory: desktop/src-tauri
        run: cargo test

  frontend-linting-and-tests:
    name: Frontend Linting and Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.13.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.4.1"
          cache: "pnpm"
          cache-dependency-path: desktop/pnpm-lock.yaml

      - name: Install dependencies
        working-directory: desktop
        run: pnpm install --frozen-lockfile

      - name: Check prettier formatting
        working-directory: desktop
        run: pnpm prettier --check .

      - name: Run tests
        working-directory: desktop
        run: pnpm test

      # - name: Build
      #   working-directory: desktop
      #   run: pnpm build
