name: On Pull Requests

on:
  pull_request:
    branches:
      - main

concurrency:
  # Cancel any running workflow for the same branch when new commits are pushed.
  # We group both by ref_name (available when CI is triggered by a push to a branch/tag)
  # and head_ref (available when CI is triggered by a PR).
  group: "${{ github.ref_name }}-${{ github.head_ref }}"
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  linting-and-tests:
    name: Linting and Tests
    uses: ./.github/workflows/linting-and-tests.yml

  claude-update-claude-md:
    name: Claude Update CLAUDE.md
    runs-on: ubuntu-latest
    steps:
      - name: Run Claude Code
        uses: anthropics/claude-code-action@e26577a930883943cf9d90885cd1e8da510078dd # beta tag
        with:
          direct_prompt: |
            Update the CLAUDE.md file to reflect the changes made in this PR.
