name: On Pull Requests

on:
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  # Cancel any running workflow for the same branch when new commits are pushed.
  # We group both by ref_name (available when CI is triggered by a push to a branch/tag)
  # and head_ref (available when CI is triggered by a PR).
  group: "${{ github.ref_name }}-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  linting-and-tests:
    name: Linting and Tests
    permissions:
      contents: read
      security-events: write
    uses: ./.github/workflows/linting-and-tests.yml

  claude-code:
    name: Claude Code
    runs-on: ubuntu-latest
    # Optional: Filter by PR author
    # if: |
    #   github.event.pull_request.user.login == 'external-contributor' ||
    #   github.event.pull_request.user.login == 'new-developer' ||
    #   github.event.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR'
    # Don't run if PR is from release-please bot or is a WIP PR
    if: |
      github.event.pull_request.head.ref != 'release-please--branches--main' && !contains(github.event.pull_request.title, '[WIP]')
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: read # Required for Claude to read CI results on PRs
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 10 # give Claude a bit more context
          persist-credentials: true # credentials are needed here as Claude will use them to read stuffs

      - name: Run Claude Code
        uses: anthropics/claude-code-action@e26577a930883943cf9d90885cd1e8da510078dd # beta tag
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # Optional: Use sticky comments to make Claude reuse the same comment on subsequent pushes to the same PR
          use_sticky_comment: true

          # Optional: Specify model (defaults to Claude Sonnet 4, uncomment for Claude Opus 4)
          model: "claude-opus-4-20250514"
          fallback_model: "claude-sonnet-4-20250514"

          # This is an optional setting that allows Claude to read CI results on PRs
          # See https://github.com/anthropics/claude-code-action?tab=readme-ov-file#additional-permissions-for-cicd-integration
          additional_permissions: |
            actions: read

          direct_prompt: |
            So I want you to do a few things to help with the current pull request:
            1. Update the CLAUDE.md file to reflect the changes made in this PR.
            2. If the pull request description is missing, add one based on the changes.
            3. Please review this pull request and provide feedback on the below items, be constructive and helpful in your feedback:
              - Code quality and best practices
              - Potential bugs or issues
              - Performance considerations
              - Security concerns
              - Test coverage
