{{- if .Values.archestra.ingress.enabled -}}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "archestra-platform.fullname" . }}-backend-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "archestra-platform.labels" . | nindent 4 }}
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /health
    port: 9000
{{- end }}